# 라이브러리로딩

In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
pd.set_option('display.max_columns', 150)

In [3]:
files = os.listdir('./data_version2')
print(len(files))
print(files)

8
['geolocation_olist_public_dataset.csv', 'olist_classified_public_dataset.csv', 'olist_public_dataset_v2.csv', 'olist_public_dataset_v2_customers.csv', 'payments_olist_public_dataset.csv', 'product_category_name_translation.csv', 'product_measures_olist_public_dataset_.csv', 'sellers_olist_public_dataset_.csv']

In [4]:
dir = "./data_version2/"
datasets = {}

datasets['geolocation'] = pd.read_csv(dir + 'geolocation_olist_public_dataset.csv', dtype = {'zip_code_prefix' : str})
datasets['classified'] = pd.read_csv(dir + 'olist_classified_public_dataset.csv', dtype = {'customer_zip_code_prefix' : str},
                         parse_dates = ['order_purchase_timestamp', 'order_aproved_at', 'order_estimated_delivery_date', 'order_delivered_customer_date', 'review_creation_date', 'review_answer_timestamp'])
datasets['dataset'] = pd.read_csv(dir + 'olist_public_dataset_v2.csv', dtype = {'customer_zip_code_prefix' : str},
                      parse_dates = ['order_purchase_timestamp', 'order_aproved_at', 'order_estimated_delivery_date', 'order_delivered_customer_date', 'review_creation_date', 'review_answer_timestamp'])
datasets['customers'] = pd.read_csv(dir + 'olist_public_dataset_v2_customers.csv')
datasets['payments'] = pd.read_csv(dir + 'payments_olist_public_dataset.csv')
datasets['translation'] = pd.read_csv(dir + 'product_category_name_translation.csv')
datasets['product_measures'] = pd.read_csv(dir + 'product_measures_olist_public_dataset_.csv')
datasets['sellers'] = pd.read_csv(dir + 'sellers_olist_public_dataset_.csv', dtype = {'seller_zip_code_prefix' : str})

In [12]:
for key, value in datasets.items():
    print(f'--------------{key}----------------')
    print(value.shape);print()
    print(value.info());print()
    for col, series in value.iteritems():
        print(f'# <{col}>')
        print('number of unique values =', series.nunique())
        print('unique values =', series.unique()[0:10])
        # value_counts()
        # unique()
        # drop_duplicates()
    # print(value.head())
    #for col, series in value.iteritems():
        #length = set(series.apply(lambda x : len(str(x))))
        #print(f'{col}내 값의 길이 : {length}')

--------------geolocation----------------
(323016, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 323016 entries, 0 to 323015
Data columns (total 5 columns):
zip_code_prefix    323016 non-null object
city               323016 non-null object
state              323016 non-null object
lat                323016 non-null float64
lng                323016 non-null float64
dtypes: float64(2), object(3)
memory usage: 12.3+ MB
None

# <zip_code_prefix>
number of unique values = 851
unique values = ['010' '011' '012' '013' '014' '015' '020' '021' '022' '023']
# <city>
number of unique values = 5419
unique values = ['sao paulo' 'sao jose dos campos' 'osasco' 'carapicuiba' 'barueri'
 'santana de parnaiba' 'pirapora do bom jesus' 'itapevi' 'jandira'
 'taboao da serra']
# <state>
number of unique values = 27
unique values = ['sp' 'rj' 'es' 'mg' 'ba' 'se' 'pe' 'al' 'pb' 'rn']
# <lat>
number of unique values = 275588
unique values = [-23.54780696 -23.54608113 -23.54098383 -23.54675842 -23.54636175
 -23.54463184 -23.54045128 -23.54020741 -23.54895849 -23.5479735 ]
# <lng>
number of unique values = 275614
unique values = [-46.63612182 -46.6448203  -46.64256856 -46.64577103 -46.64307284
 -46.6339372  -46.64357022 -46.63530381 -46.63486176 -46.6334685 ]
--------------classified----------------
(3584, 34)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3584 entries, 0 to 3583
Data columns (total 34 columns):
Unnamed: 0                       3584 non-null int64
id                               3584 non-null int64
order_status                     3584 non-null object
order_products_value             3584 non-null float64
order_freight_value              3584 non-null float64
order_items_qty                  3584 non-null int64
order_sellers_qty                3584 non-null int64
order_purchase_timestamp         3584 non-null datetime64[ns]
order_aproved_at                 3584 non-null datetime64[ns]
order_estimated_delivery_date    3584 non-null datetime64[ns]
order_delivered_customer_date    3467 non-null datetime64[ns]
customer_city                    3584 non-null object
customer_state                   3584 non-null object
customer_zip_code_prefix         3584 non-null object
product_category_name            3584 non-null object
product_name_lenght              3584 non-null int64
product_description_lenght       3584 non-null int64
product_photos_qty               3584 non-null int64
review_score                     3584 non-null int64
review_comment_title             0 non-null float64
review_comment_message           3584 non-null object
review_creation_date             3584 non-null datetime64[ns]
review_answer_timestamp          3584 non-null datetime64[ns]
votes_before_estimate            3584 non-null int64
votes_delayed                    3584 non-null int64
votes_low_quality                3584 non-null int64
votes_return                     3584 non-null int64
votes_not_as_anounced            3584 non-null int64
votes_partial_delivery           3584 non-null int64
votes_other_delivery             3584 non-null int64
votes_other_order                3584 non-null int64
votes_satisfied                  3584 non-null int64
most_voted_subclass              3413 non-null object
most_voted_class                 3413 non-null object
dtypes: datetime64[ns](6), float64(3), int64(17), object(8)
memory usage: 952.1+ KB
None

# <Unnamed: 0>
number of unique values = 3584
unique values = [0 1 2 3 4 5 6 7 8 9]
# <id>
number of unique values = 3584
unique values = [ 1  2  3  4  5  6  7  8  9 10]
# <order_status>
number of unique values = 5
unique values = ['delivered' 'shipped' 'processing' 'invoiced' 'canceled']
# <order_products_value>
number of unique values = 1092
unique values = [ 89.99  69.    99.8   87.    99.9   39.99 229.9  164.9   89.9   99.99]
# <order_freight_value>
number of unique values = 1597
unique values = [14.38 15.23 15.86 12.74 17.95  0.15 30.01  8.41 40.62 19.94]
# <order_items_qty>
number of unique values = 7
unique values = [1 2 3 6 5 4 8]
# <order_sellers_qty>
number of unique values = 10
unique values = [ 1  4  2  6  3 12  8  9  7 10]
# <order_purchase_timestamp>
number of unique values = 3177
unique values = ['2017-08-30T11:41:01.000000000' '2017-09-26T09:13:36.000000000'
 '2018-01-15T15:50:42.000000000' '2018-02-04T11:16:42.000000000'
 '2017-12-07T11:58:42.000000000' '2017-11-02T11:33:03.000000000'
 '2017-11-26T23:58:24.000000000' '2017-12-08T21:13:04.000000000'
 '2017-07-04T16:12:36.000000000' '2017-11-29T04:25:45.000000000']
# <order_aproved_at>
number of unique values = 3204
unique values = ['2017-08-30T11:55:08.970352000' '2017-09-26T09:28:10.922048000'
 '2018-01-17T07:29:56.419769000' '2018-02-06T05:31:50.990164000'
 '2017-12-08T02:36:49.587515000' '2017-11-04T08:05:48.050186000'
 '2017-11-27T00:18:31.179577000' '2017-12-08T21:32:36.905274000'
 '2017-07-04T16:24:00.454971000' '2017-12-01T11:32:01.170224000']
# <order_estimated_delivery_date>
number of unique values = 257
unique values = ['2017-09-21T00:00:00.000000000' '2017-10-24T00:00:00.000000000'
 '2018-02-05T00:00:00.000000000' '2018-03-13T00:00:00.000000000'
 '2018-01-03T00:00:00.000000000' '2017-11-23T00:00:00.000000000'
 '2017-12-28T00:00:00.000000000' '2017-12-27T00:00:00.000000000'
 '2017-07-24T00:00:00.000000000' '2017-12-29T00:00:00.000000000']
# <order_delivered_customer_date>
number of unique values = 3090
unique values = ['2017-09-08T20:35:27.276847000' '2017-09-29T21:13:04.984841000'
 '2018-01-23T17:51:31.134866000' '2018-02-20T19:38:06.633080000'
 '2017-12-19T22:33:18.952512000' '2017-11-09T19:09:10.241896000'
 '2017-12-19T14:13:52.655799000' '2017-12-26T16:09:57.768207000'
 '2017-07-10T16:35:53.500041000' '2017-12-18T15:22:57.104615000']
# <customer_city>
number of unique values = 897
unique values = ['Belo Horizonte' 'Pocos de Caldas' 'Sao Jose dos Campos' 'Ribeirao Preto'
 'RIO DE JANEIRO' 'Sao Paulo' 'Floresta' 'SAO PAULO' 'Juquitiba'
 'Salvador']
# <customer_state>
number of unique values = 26
unique values = ['MG' 'SP' 'RJ' 'PE' 'BA' 'CE' 'ES' 'PR' 'RN' 'RS']
# <customer_zip_code_prefix>
number of unique values = 684
unique values = ['308' '377' '122' '140' '205' '20' '564' '83' '69' '403']
# <product_category_name>
number of unique values = 60
unique values = ['beleza_saude' 'brinquedos' 'ferramentas_jardim' 'informatica_acessorios'
 'cama_mesa_banho' 'fashion_bolsas_e_acessorios' 'moveis_decoracao'
 'relogios_presentes' 'malas_acessorios' 'livros_interesse_geral']
# <product_name_lenght>
number of unique values = 55
unique values = [59 50 45 60 53 54 47 58 46 39]
# <product_description_lenght>
number of unique values = 1243
unique values = [ 492  679  341  411  189  386 1120  448  482 1390]
# <product_photos_qty>
number of unique values = 14
unique values = [ 3  4  2  1  8  7  6  5  9 11]
# <review_score>
number of unique values = 5
unique values = [5 1 4 3 2]
# <review_comment_title>
number of unique values = 0
unique values = [nan]
# <review_comment_message>
number of unique values = 2812
unique values = ['tudo certo' 'o produto chegou antes de prazo parabens pela pontualidade'
 'foi adquirido 6 itens desta loja onde até o momento não foi entregue um 1 unidade pendente meia lua meia bola esfera alumínio 34cm vermelho solicito posicionamento da empresa para recebimento'
 'achei a entrega um pouco demorada'
 'comprei 02 jogos de lencois de cetim e uma colcha mas até agora só recebi o jogo de lencol cor cobre o que houve'
 'apesar de ser da mesma loja os produtos vieram em 3 caixas separadas e em datas diferentes fazendo o sistema do stark confirmar a chegada dos 3 logo na primeira entrega'
 'não gostei de ter que ir retirar no correio quanto ao produto ainda vou monta lo e fixar na parede depois retorno com outra avaliação a principio ele parece estar ok'
 'recomendo essa loja entrega antes do prazo'
 'produto entregue dentro do prazo' 'adorei nota 10']
# <review_creation_date>
number of unique values = 319
unique values = ['2017-09-09T00:00:00.000000000' '2017-09-30T00:00:00.000000000'
 '2018-01-24T00:00:00.000000000' '2018-02-21T00:00:00.000000000'
 '2017-12-20T00:00:00.000000000' '2017-11-10T00:00:00.000000000'
 '2017-12-27T00:00:00.000000000' '2017-07-11T00:00:00.000000000'
 '2017-12-19T00:00:00.000000000' '2018-02-27T00:00:00.000000000']
# <review_answer_timestamp>
number of unique values = 3114
unique values = ['2017-09-10T03:27:54.000000000' '2017-10-03T05:34:20.000000000'
 '2018-02-02T17:42:43.000000000' '2018-02-22T02:09:12.000000000'
 '2017-12-23T04:17:03.000000000' '2017-11-13T22:28:12.000000000'
 '2017-12-21T12:44:54.000000000' '2017-12-27T23:23:17.000000000'
 '2017-07-14T14:42:17.000000000' '2017-12-21T20:10:55.000000000']
# <votes_before_estimate>
number of unique values = 4
unique values = [0 3 2 1]
# <votes_delayed>
number of unique values = 7
unique values = [0 3 1 2 6 5 4]
# <votes_low_quality>
number of unique values = 4
unique values = [0 1 3 2]
# <votes_return>
number of unique values = 5
unique values = [0 2 1 3 4]
# <votes_not_as_anounced>
number of unique values = 7
unique values = [0 1 2 3 4 6 5]
# <votes_partial_delivery>
number of unique values = 6
unique values = [0 3 1 2 5 6]
# <votes_other_delivery>
number of unique values = 4
unique values = [0 1 3 2]
# <votes_other_order>
number of unique values = 5
unique values = [0 1 2 4 3]
# <votes_satisfied>
number of unique values = 6
unique values = [3 0 1 2 6 5]
# <most_voted_subclass>
number of unique values = 9
unique values = ['satisfeito' 'antes_prazo' 'entrega_parcial' 'atrasado' nan
 'outro_entrega' 'devolucao' 'diferente_do_anunciado' 'baixa_qualidade'
 'outro_pedido']
# <most_voted_class>
number of unique values = 3
unique values = ['satisfeito_com_pedido' 'problemas_de_entrega' nan
 'problemas_de_qualidade']
--------------dataset----------------
(100000, 25)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
order_id                         100000 non-null object
order_status                     100000 non-null object
order_products_value             100000 non-null float64
order_freight_value              100000 non-null float64
order_items_qty                  100000 non-null int64
order_sellers_qty                100000 non-null int64
order_purchase_timestamp         100000 non-null datetime64[ns]
order_aproved_at                 99982 non-null datetime64[ns]
order_estimated_delivery_date    100000 non-null datetime64[ns]
order_delivered_customer_date    97595 non-null datetime64[ns]
customer_id                      100000 non-null object
customer_city                    100000 non-null object
customer_state                   100000 non-null object
customer_zip_code_prefix         100000 non-null object
product_category_name            100000 non-null object
product_name_lenght              100000 non-null int64
product_description_lenght       100000 non-null int64
product_photos_qty               100000 non-null int64
product_id                       100000 non-null object
review_id                        100000 non-null object
review_score                     100000 non-null int64
review_comment_title             8262 non-null object
review_comment_message           42489 non-null object
review_creation_date             100000 non-null datetime64[ns]
review_answer_timestamp          100000 non-null datetime64[ns]
dtypes: datetime64[ns](6), float64(2), int64(6), object(11)
memory usage: 19.1+ MB
None

# <order_id>
number of unique values = 96264
unique values = ['b95df3cef5297e79ef709ba256518f6f' '59af46052a799e80e2f0c665c587731d'
 'a3e6136894621db402a772c6bc72a12a' 'b675ea5a618922f6e679e30531b8957b'
 '195a8be6794c487fe6cfbb97b7c61902' '80dbbd6f2282898dbf912a2ec668175f'
 '0f374228bdae432c9bdda69f21ccd261' 'd02366be68b26b954269321e475a79fe'
 'd42c3af33e0f04b3d5f012b6559e70c9' '92e9390c69bcb745fe059efdf93cac2a']
# <order_status>
number of unique values = 7
unique values = ['delivered' 'canceled' 'shipped' 'invoiced' 'processing' 'unavailable'
 'approved']
# <order_products_value>
number of unique values = 6080
unique values = [349.9   15.   238.9   29.99 295.99 160.    25.    43.3   89.9   40.  ]
# <order_freight_value>
number of unique values = 7644
unique values = [13.84 15.1  18.   18.23 47.65 19.   19.09 17.44 14.8   8.88]
# <order_items_qty>
number of unique values = 15
unique values = [ 1  2  3  4 10  6  5  8 12 20]
# <order_sellers_qty>
number of unique values = 15
unique values = [ 1  2  3  4  9  6  8  5  7 10]
# <order_purchase_timestamp>
number of unique values = 95706
unique values = ['2017-01-31T17:19:01.000000000' '2017-09-09T19:52:54.000000000'
 '2017-01-30T17:00:09.000000000' '2018-03-11T18:18:36.000000000'
 '2017-04-20T08:01:08.000000000' '2018-04-03T13:25:35.000000000'
 '2018-06-11T19:45:54.000000000' '2017-08-27T15:29:59.000000000'
 '2017-03-13T15:43:08.000000000' '2018-05-07T21:13:12.000000000']
# <order_aproved_at>

number of unique values = 96239
unique values = ['2017-02-01T02:41:21.549551000' '2017-09-10T20:03:31.535281000'
 '2017-01-30T17:31:25.438253000' '2018-03-11T18:30:37.931962000'
 '2017-04-25T08:05:40.405383000' '2018-04-03T13:48:55.262983000'
 '2018-06-11T20:22:07.752257000' '2017-08-27T15:45:22.034556000'
 '2017-03-13T15:43:08.000000000' '2018-05-07T21:31:19.636651000']
# <order_estimated_delivery_date>
number of unique values = 480
unique values = ['2017-03-15T00:00:00.000000000' '2017-10-02T00:00:00.000000000'
 '2017-03-07T00:00:00.000000000' '2018-04-03T00:00:00.000000000'
 '2017-05-24T00:00:00.000000000' '2018-05-07T00:00:00.000000000'
 '2018-07-04T00:00:00.000000000' '2017-09-13T00:00:00.000000000'
 '2017-04-04T00:00:00.000000000' '2018-05-17T00:00:00.000000000']
# <order_delivered_customer_date>
number of unique values = 93915
unique values = ['2017-02-06T11:04:24.154259000' '2017-09-13T20:17:41.296915000'
 '2017-02-06T15:43:04.758566000' '2018-04-03T20:36:43.778451000'
 '2017-05-04T18:47:45.721758000' '2018-04-18T23:22:45.922709000'
 '2018-06-29T20:52:35.173465000' '2017-08-30T18:10:20.939031000'
 '2017-03-22T13:08:38.524197000' '2018-05-10T23:25:30.303778000']
# <customer_id>
number of unique values = 96264
unique values = ['297dcf281305aabfee256d313076af2b' 'b7563d94162ed0aa3f8d9cada4bcc536'
 'f102cb15ec41ca30fa2902da06495f6b' 'e33c250311160298e5b457ca52720a35'
 '8a8f7c9a4450f17ba3ee25a5ba821bc7' 'b6abf1bfc44b9480d8c0f06c3d7ddcdb'
 '99bd38325725d4fbce9115a451d60454' '0ffda100257bd2c6ddb2d5d12a972b65'
 '25c2777ca6e69ffaf3ff45bc8db161e7' '0fd9913b2eabb107bed0603b5f6f4bf6']
# <customer_city>
number of unique values = 4121
unique values = ['Guaratuba' 'Uberlandia' 'Itapevi' 'Goiania' 'Recife' 'Rio Grande'
 'Salvador' 'Jandira' 'Belo Horizonte' 'Sao Paulo']
# <customer_state>
number of unique values = 27
unique values = ['PR' 'MG' 'SP' 'GO' 'PE' 'RS' 'BA' 'AC' 'CE' 'SC']
# <customer_zip_code_prefix>
number of unique values = 851
unique values = ['832' '384' '066' '743' '511' '962' '402' '301' '013' '375']
# <product_category_name>
number of unique values = 71
unique values = ['beleza_saude' 'informatica_acessorios' 'automotivo' 'cama_mesa_banho'
 'moveis_decoracao' 'esporte_lazer' 'perfumaria' 'utilidades_domesticas'
 'telefonia' 'relogios_presentes']
# <product_name_lenght>
number of unique values = 63
unique values = [51 44 55 49 48 53  9 54 46 57]
# <product_description_lenght>
number of unique values = 2727
unique values = [ 625 1428  637  617  558 1422  369  380  245  490]
# <product_photos_qty>
number of unique values = 19
unique values = [ 1  2  6  3  4  5  7  8  9 10]
# <product_id>
number of unique values = 24447
unique values = ['6cdd53843498f92890544667809f1595' 'ae5cad88462eb7b7b61401e31c45618e'
 '0c9ff9d8ed9b9bdd825487b3a66e05f5' 'ad0a798e7941f3a5a2fb8139cb62ad78'
 'eaf2046d4c87809247a30050ea13df03' '167752e318335bf6bdd6906c4c470266'
 'a30ea5a9dbd95db5a674c4beadb4fb0d' '3cb0ece3f5f0b8121a53635c9f783aa5'
 '99a4788cb24856965c36a24e339b6058' 'c7fd13b5e515bffdab855d0812842edb']
# <review_id>
number of unique values = 96264
unique values = ['b95df3cef5297e79ef709ba256518f6f' '59af46052a799e80e2f0c665c587731d'
 'a3e6136894621db402a772c6bc72a12a' 'b675ea5a618922f6e679e30531b8957b'
 '195a8be6794c487fe6cfbb97b7c61902' '80dbbd6f2282898dbf912a2ec668175f'
 '0f374228bdae432c9bdda69f21ccd261' 'd02366be68b26b954269321e475a79fe'
 'd42c3af33e0f04b3d5f012b6559e70c9' '92e9390c69bcb745fe059efdf93cac2a']
# <review_score>
number of unique values = 5
unique values = [5 4 3 1 2]
# <review_comment_title>
number of unique values = 3365
unique values = [nan 'Vendedor confiável' 'Muito bom' 'Recomendo.'
 'Recebi o produto incomple' 'Bom ' 'decepcionado' 'Recomendo!'
 'excelente' 'Ótima ']
# <review_comment_message>
number of unique values = 33782
unique values = [nan 'entrega em 2 dias produto c boa qualidade otimo custo beneficio'
 'produto veio antes do prazo informado muito obrigado pela agilidade'
 'chegou bem antes do prazo ótimo vendedor' 'gostei do produto'
 'o produto veio certinho muito bem embalado e bem antes do prazo era pra chegae dia 26 e chegou dia 9 muito bom mesmo'
 'produtos em perfeitas condições e entrega dentro do prazo'
 'veio apenas um produto porém foi cobrado 2 produtos já fiz a reclamação e até o momento não obtive resposta'
 'gostei do celular minha mae achou lindo para pessoa idosa que nao sabe mecher muito esta perfeito so nao conceguir instalar o whatapp a firefox bem que poderia da um jeito'
 'a mercadoria chegou antes do prazo final recomendo']
# <review_creation_date>
number of unique values = 668
unique values = ['2017-02-07T00:00:00.000000000' '2017-09-14T00:00:00.000000000'
 '2018-04-04T00:00:00.000000000' '2017-05-05T00:00:00.000000000'
 '2018-04-19T00:00:00.000000000' '2018-06-30T00:00:00.000000000'
 '2017-08-31T00:00:00.000000000' '2017-03-23T00:00:00.000000000'
 '2018-05-11T00:00:00.000000000' '2017-07-13T00:00:00.000000000']
# <review_answer_timestamp>
number of unique values = 95884
unique values = ['2017-02-09T02:37:37.000000000' '2017-09-15T03:43:47.000000000'
 '2017-02-10T14:18:53.000000000' '2018-04-05T02:52:31.000000000'
 '2017-05-08T15:20:18.000000000' '2018-04-20T12:31:04.000000000'
 '2018-07-04T01:36:31.000000000' '2017-09-12T06:14:48.000000000'
 '2017-03-24T17:26:18.000000000' '2018-05-12T05:40:51.000000000']
--------------customers----------------
(96264, 2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96264 entries, 0 to 96263
Data columns (total 2 columns):
customer_id           96264 non-null object
customer_unique_id    96264 non-null object
dtypes: object(2)
memory usage: 1.5+ MB
None

# <customer_id>
number of unique values = 96264
unique values = ['0000ca4ff2795842fd6b122c6d974468' '00010f206878ba01f199aec4237de72e'
 '00012a2ce6f8dcda20d059ce98491703' '000161a058600d5901f007fab4c27140'
 '00017f1d6cce0d56046219a2cfabcbbb' '0001b5f91fc9b5a10f758ddebef66ee2'
 '0001dad3e429b2831bf4e392170a8e8c' '0001fd6190edaaf884bcaf3d49edf079'
 '000214e5477739663f0e8c1f6108189b' '0002414f95344307404f0ace7a26f1d5']
# <customer_unique_id>
number of unique values = 92516
unique values = ['ac0e5d7f07043dd32831bdad3b99ad26' '4ed24aaed4079fe0661c0e4b3b420dff'
 '7e0e291c0f4fc2d69208954d26ed0586' 'ff1dcb27ea444eddb94ea5fea77b875c'
 '237130c4b6717031ed62d9d0b16fd94f' '6b5d56936cf12116fb5d22c6a1719b94'
 '59c4caa59a6841fc634bdb07ebfc7020' '2221b1efb226117750cbea106c00c8e1'
 'daea776f80ad68c47557b3877361398c' '2bde416eaa7e490dc44b7099178c9155']
--------------payments----------------
(97433, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97433 entries, 0 to 97432
Data columns (total 5 columns):
order_id        97433 non-null object
installments    97433 non-null int64
sequential      97433 non-null int64
payment_type    97433 non-null object
value           97433 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.7+ MB
None

# <order_id>
number of unique values = 93000
unique values = ['25e8ea4e93396b6fa0d3dd708e76c1bd' 'ba78997921bbcdc1373bb41e913ab953'
 '42fdf880ba16b47b59251dd489d4441a' '771ee386b001f06208a7419e4fc1bbd7'
 '62fe0bd75deb58982ebf8e53a128a301' '0573b5e23cbd798006520e1d5b4c6714'
 '8b00bea9bf7bedeb94e6b624a38889f6' '5f38dfdb889c2d46939ed9f49bb92092'
 '616105c9352a9668c38303ad44e056cd' 'cf95215a722f3ebf29e6bbab87a29e61']
# <installments>
number of unique values = 25
unique values = [ 1  8  2  5  4 10  3  7  6 16]
# <sequential>
number of unique values = 29
unique values = [ 1  2  5  3  8  7  4  6 10 11]
# <payment_type>
number of unique values = 4
unique values = ['credit_card' 'boleto' 'voucher' 'debit_card']
# <value>
number of unique values = 26724
unique values = [ 65.71 107.78 128.45  81.16  15.82  51.95  39.88 118.26  75.78 102.66]
--------------translation----------------
(71, 2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
product_category_name            71 non-null object
product_category_name_english    71 non-null object
dtypes: object(2)
memory usage: 1.2+ KB
None

# <product_category_name>
number of unique values = 71
unique values = ['beleza_saude' 'informatica_acessorios' 'automotivo' 'cama_mesa_banho'
 'moveis_decoracao' 'esporte_lazer' 'perfumaria' 'utilidades_domesticas'
 'telefonia' 'relogios_presentes']
# <product_category_name_english>
number of unique values = 71
unique values = ['health_beauty' 'computers_accessories' 'auto' 'bed_bath_table'
 'furniture_decor' 'sports_leisure' 'perfumery' 'housewares' 'telephony'
 'watches_gifts']
--------------product_measures----------------
(24439, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24439 entries, 0 to 24438
Data columns (total 5 columns):
product_id           24439 non-null object
product_weight_g     24439 non-null float64
product_length_cm    24439 non-null float64
product_height_cm    24439 non-null float64
product_width_cm     24439 non-null float64
dtypes: float64(4), object(1)
memory usage: 954.7+ KB
None

# <product_id>
number of unique values = 24439
unique values = ['00faa46f36261af8bbf3a4d37fa4841b' 'b497d0032ea073dd58bbd2d7809d25b3'
 '96bd76ec8810374ed1b65e291975717f' '506110a1603e772a8ff52ea1f0b0431d'
 'feb593f17c2f51af2932dbba3e99f1cb' '732bd381ad09e530fe0a5f457d81becb'
 '2548af3e6e77a690cf3eb6368e9ab61e' '3f890febf04d23fbbb967485295fbea8'
 '90467a0531183f8fd2cc76ca735df8a5' '8c92109888e8cdf9d66dc7e463025574']
# <product_weight_g>
number of unique values = 637
unique values = [  100.   750.   200.    50. 18350.   900.  1200.  3500.   600.  1100.]
# <product_length_cm>
number of unique values = 161
unique values = [21. 23. 16. 35. 68. 40. 34. 41. 17. 29.]
# <product_height_cm>
number of unique values = 197
unique values = [ 9.  5.  6. 13.  4. 20.  8. 16. 15. 10.]
# <product_width_cm>
number of unique values = 156
unique values = [14.  15.  19.5 13.  26.  41.  40.  16.  25.  12. ]
--------------sellers----------------
(98981, 6)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98981 entries, 0 to 98980
Data columns (total 6 columns):
order_id                  98981 non-null object
product_id                98981 non-null object
seller_id                 98981 non-null object
seller_zip_code_prefix    98981 non-null object
seller_city               98981 non-null object
seller_state              98981 non-null object
dtypes: object(6)
memory usage: 4.5+ MB
None

# <order_id>
number of unique values = 96247
unique values = ['0faabac07131235fc5d9d711471cb4db' '970f41d57d6e21afa7b8c701b09acb95'
 'b674ed44cc3f6a869249421debebe104' 'cbe9eae36605cf2bd005c6bc1ae5f864'
 'f562f8a4adf5a459176f7170d0da220d' 'faeb0ac7f6e1480f3dd14e5cd802dc8a'
 '875022b850d729e6090f2e0719518e6b' '273f82958d907705dde15be4062c6888'
 '1ae28e017017595bfac368c574704d1a' 'bd653591a61bb3875b4f0f890696a61f']
# <product_id>
number of unique values = 24440
unique values = ['40b09f33e646d488df2ca6fec4082d50' 'd1c427060a0f73f6b889a5c7c61f2ac4'
 'bd7cd34fc6d02e730221b11edc354aae' '0e95d6eef2bedaf4ecf3c33f78199059'
 '9a3a44b7cc16f2592b2110e4205edf97' '687ada1b5c787ece71130a5ec0123567'
 '45f7c48e7ead07eb1afd9aebfe6de326' '154e7e31ebfa092203795c972e5804a6'
 'efe4838ca7d6540e8fa0ea4cf5660b46' 'f731f8587d4088c174397e010cf892a9']
# <seller_id>
number of unique values = 2104
unique values = ['3d871de0142ce09b7081e2b9d1733cb1' 'a1043bafd471dff536d0c462352beb48'
 '46dc3b2cc0980fb8ec44634e21d2718e' 'dc4a0fc896dc34b0d5bfec8438291c80'
 '5a8e7d5003a1f221f9e1d6e411de7c23' '05a940b4ecae36cadfd8e93bd9c43257'
 '33a17d60c64393351ebf1ef860f4e0f2' 'cc419e0650a3c5ba77189a1882b7556a'
 'b7ed9fb14c8eadb37adb9c45d67ab0fb' '128639473a139ac0f3e5f5ade55873a5']
# <seller_zip_code_prefix>

number of unique values = 427
unique values = ['132' '371' '222' '149' '130' '743' '915' '090' '123' '870']
# <seller_city>
number of unique values = 476
unique values = ['campo limpo paulista' 'ilicinea' 'rio de janeiro' 'ibitinga' 'campinas'
 'goiania' 'porto alegre' 'santo andre' 'jacarei' 'maringa']
# <seller_state>
number of unique values = 22
unique values = ['SP' 'MG' 'RJ' 'GO' 'RS' 'PR' 'SC' 'DF' 'BA' 'CE']

In [20]:
datasets['classified'].iloc[:, 23:34].nunique()

votes_before_estimate     4
votes_delayed             7
votes_low_quality         4
votes_return              5
votes_not_as_anounced     7
votes_partial_delivery    6
votes_other_delivery      4
votes_other_order         5
votes_satisfied           6
most_voted_subclass       9
most_voted_class          3
dtype: int64

In [28]:
datasets['classified'][datasets['classified'].iloc[:, 24]==(4)]

,Unnamed: 0,id,order_status,order_products_value,order_freight_value,order_items_qty,order_sellers_qty,order_purchase_timestamp,order_aproved_at,order_estimated_delivery_date,order_delivered_customer_date,customer_city,customer_state,customer_zip_code_prefix,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,votes_before_estimate,votes_delayed,votes_low_quality,votes_return,votes_not_as_anounced,votes_partial_delivery,votes_other_delivery,votes_other_order,votes_satisfied,most_voted_subclass,most_voted_class
3052,3052,3053,delivered,140.9,17.11,1,2,2018-01-05 12:11:48,2018-01-05 13:47:25.945835,2018-02-06,2018-01-26 18:27:32.502926,RIO DE JANEIRO,RJ,200,esporte_lazer,51,1456,1,2,NaN,a entrega está demorada 20 dias comprei 2 prod...,2018-01-27,2018-01-28 13:52:56,0,4,0,0,0,2,0,0,0,entrega_parcial,problemas_de_entrega

In [6]:
for key, value in datasets.items():
    print(f'--------------{key}----------------')
    print(value.head())

--------------customers----------------
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

  customer_zip_code_prefix          customer_city customer_state
0                    14409                 franca             SP
1                    09790  sao bernardo do campo             SP
2                    01151              sao paulo             SP
3                    08775        mogi das cruzes             SP
4                    13056               campinas             SP
--------------geolocation----------------
  geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                       01037       -23.545621       -46.639292
1                       01046       -23.546081       -46.644820
2                       01046       -23.546129       -46.642951
3                       01041       -23.544392       -46.639499
4                       01035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP
--------------orders----------------
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00
--------------order_items----------------
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14
--------------order_payments----------------
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45
--------------order_reviews----------------
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53
--------------products----------------
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0
--------------sellers----------------
                          seller_id seller_zip_code_prefix        seller_city  \
0  3442f8959a84dea7ee197c632cb2df15                  13023           campinas
1  d1b65fc7debc3361ea86b5f14c68d2e2                  13844         mogi guacu
2  ce3ad9de960102d0677a81f5d0bb7b2d                  20031     rio de janeiro
3  c0f3eea2e14555b6faeea3dd58c1b1c3                  04195          sao paulo
4  51a04a8a6bdcb23deccc82b0b80742cf                  12914  braganca paulista

  seller_state
0           SP
1           SP
2           RJ
3           SP
4           SP

In [7]:
for key, value in datasets.items() :
    print(f'--------------{key}----------------')
    for col, series in value.iteritems():
        length = set(series.apply(lambda x : len(str(x))))
        print(f'{col}내 값의 길이 : {length}')

--------------customers----------------
customer_id내 값의 길이 : {32}
customer_unique_id내 값의 길이 : {32}
customer_zip_code_prefix내 값의 길이 : {5}
customer_city내 값의 길이 : {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32}
customer_state내 값의 길이 : {2}
--------------geolocation----------------
geolocation_zip_code_prefix내 값의 길이 : {5}
geolocation_lat내 값의 길이 : {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22}
geolocation_lng내 값의 길이 : {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}
geolocation_city내 값의 길이 : {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 38}
geolocation_state내 값의 길이 : {2}
--------------orders----------------
order_id내 값의 길이 : {32}
customer_id내 값의 길이 : {32}
order_status내 값의 길이 : {7, 8, 9, 10, 11}
order_purchase_timestamp내 값의 길이 : {19}
order_approved_at내 값의 길이 : {3, 19}
order_delivered_carrier_date내 값의 길이 : {3, 19}
order_delivered_customer_date내 값의 길이 : {3, 19}
order_estimated_delivery_date내 값의 길이 : {19}
--------------order_items----------------
order_id내 값의 길이 : {32}
order_item_id내 값의 길이 : {1, 2}
product_id내 값의 길이 : {32}
seller_id내 값의 길이 : {32}
shipping_limit_date내 값의 길이 : {19}
price내 값의 길이 : {3, 4, 5, 6, 7}
freight_value내 값의 길이 : {3, 4, 5, 6}
--------------order_payments----------------
order_id내 값의 길이 : {32}
payment_sequential내 값의 길이 : {1, 2}
payment_type내 값의 길이 : {10, 11, 6, 7}
payment_installments내 값의 길이 : {1, 2}
payment_value내 값의 길이 : {3, 4, 5, 6, 7, 8}
--------------order_reviews----------------
review_id내 값의 길이 : {32}
order_id내 값의 길이 : {32}
review_score내 값의 길이 : {1}
review_comment_title내 값의 길이 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26}
review_comment_message내 값의 길이 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208}
review_creation_date내 값의 길이 : {19}
review_answer_timestamp내 값의 길이 : {19}
--------------products----------------
product_id내 값의 길이 : {32}
product_category_name내 값의 길이 : {3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 27, 29, 30, 32, 33, 34, 45, 46}
product_name_lenght내 값의 길이 : {3, 4}
product_description_lenght내 값의 길이 : {3, 4, 5, 6}
product_photos_qty내 값의 길이 : {3, 4}
product_weight_g내 값의 길이 : {3, 4, 5, 6, 7}
product_length_cm내 값의 길이 : {3, 4, 5}
product_height_cm내 값의 길이 : {3, 4, 5}
product_width_cm내 값의 길이 : {3, 4, 5}
--------------sellers----------------
seller_id내 값의 길이 : {32}
seller_zip_code_prefix내 값의 길이 : {5}
seller_city내 값의 길이 : {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 30, 31, 38, 40}
seller_state내 값의 길이 : {2}

In [8]:
orders = datasets['orders']

In [9]:
orders.order_status.astype('category').values

[delivered, delivered, delivered, delivered, delivered, ..., delivered, delivered, delivered, delivered, delivered]
Length: 99441
Categories (8, object): [approved, canceled, created, delivered, invoiced, processing, shipped, unavailable]

In [10]:
order_reviews = datasets['order_reviews']

In [11]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
review_id                  100000 non-null object
order_id                   100000 non-null object
review_score               100000 non-null int64
review_comment_title       11715 non-null object
review_comment_message     41753 non-null object
review_creation_date       100000 non-null object
review_answer_timestamp    100000 non-null object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [12]:
order_reviews.review_score.value_counts()

5    57420
4    19200
1    11858
3     8287
2     3235
Name: review_score, dtype: int64

# orders

In [13]:
orders.order_status.value_counts()

delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_status, dtype: int64

In [14]:
orders.order_status.nunique()

8

In [15]:
for key, value in datasets.items() :
    print(f'--------------{key}----------------')
    for col, series in value.iteritems():
        print(f'# <{col}>')
        print('number of unique values =', series.nunique())
        print('unique values =', series.unique())
        # value_counts()
        # unique()
        # drop_duplicates()

--------------customers----------------
# <customer_id>
number of unique values = 99441
unique values = ['06b8999e2fba1a1fbc88172c00ba8bc7' '18955e83d337fd6b2def6b18a428ac77'
 '4e7b3e00288586ebd08712fdd0374a03' ... '5e28dfe12db7fb50a4b2f691faecea5e'
 '56b18e2166679b8a959d72dd06da27f9' '274fa6071e5e17fe303b9748641082c8']
# <customer_unique_id>
number of unique values = 96096
unique values = ['861eff4711a542e4b93843c6dd7febb0' '290c77bc529b7ac935b93aa66c333dc3'
 '060e732b5b29e8181a18229c7b0b2b5e' ... 'e9f50caf99f032f0bf3c55141f019d99'
 '73c2643a0a458b49f58cea58833b192e' '84732c5050c01db9b23e19ba39899398']
# <customer_zip_code_prefix>
number of unique values = 14994
unique values = ['14409' '09790' '01151' ... '05538' '74980' '99043']
# <customer_city>
number of unique values = 4119
unique values = ['franca' 'sao bernardo do campo' 'sao paulo' ... 'monte bonito'
 'sao rafael' 'eugenio de castro']
# <customer_state>
number of unique values = 27
unique values = ['SP' 'SC' 'MG' 'PR' 'RJ' 'RS' 'PA' 'GO' 'ES' 'BA' 'MA' 'MS' 'CE' 'DF'
 'RN' 'PE' 'MT' 'AM' 'AP' 'AL' 'RO' 'PB' 'TO' 'PI' 'AC' 'SE' 'RR']
--------------geolocation----------------
# <geolocation_zip_code_prefix>
number of unique values = 19015
unique values = ['01037' '01046' '01041' ... '99910' '99920' '99952']
# <geolocation_lat>
number of unique values = 717358
unique values = [-23.54562128 -23.54608113 -23.54612897 ... -28.06886363 -28.06863888
 -28.38893188]
# <geolocation_lng>
number of unique values = 717613
unique values = [-46.63929205 -46.6448203  -46.64295148 ... -52.01296438 -52.01070525
 -51.84687132]
# <geolocation_city>
number of unique values = 8011
unique values = ['sao paulo' 'são paulo' 'sao bernardo do campo' ... 'ciríaco' 'estação'
 'vila lângaro']
# <geolocation_state>
number of unique values = 27
unique values = ['SP' 'RN' 'AC' 'RJ' 'ES' 'MG' 'BA' 'SE' 'PE' 'AL' 'PB' 'CE' 'PI' 'MA'
 'PA' 'AP' 'AM' 'RR' 'DF' 'GO' 'RO' 'TO' 'MT' 'MS' 'RS' 'PR' 'SC']
--------------orders----------------
# <order_id>
number of unique values = 99441
unique values = ['e481f51cbdc54678b7cc49136f2d6af7' '53cdb2fc8bc7dce0b6741e2150273451'
 '47770eb9100c2d0c44946d9cf07ec65d' ... '83c1379a015df1e13d02aae0204711ab'
 '11c177c8e97725db2631073c19f07b62' '66dea50a8b16d9b4dee7af250b4be1a5']
# <customer_id>
number of unique values = 99441
unique values = ['9ef432eb6251297304e76186b10a928d' 'b0830fb4747a6c6d20dea0b8c802d7ef'
 '41ce2a54c0b03bf3443c3d931a367089' ... '1aa71eb042121263aafbe80c1b562c9c'
 'b331b74b18dc79bcdf6532d51e1637c1' 'edb027a75a1449115f6b43211ae02a24']
# <order_status>
number of unique values = 8
unique values = ['delivered' 'invoiced' 'shipped' 'processing' 'unavailable' 'canceled'
 'created' 'approved']
# <order_purchase_timestamp>
number of unique values = 98875
unique values = ['2017-10-02 10:56:33' '2018-07-24 20:41:37' '2018-08-08 08:38:49' ...
 '2017-08-27 14:46:43' '2018-01-08 21:28:27' '2018-03-08 20:57:30']
# <order_approved_at>
number of unique values = 90733
unique values = ['2017-10-02 11:07:15' '2018-07-26 03:24:27' '2018-08-08 08:55:23' ...
 '2017-08-27 15:04:16' '2018-01-08 21:36:21' '2018-03-09 11:20:28']
# <order_delivered_carrier_date>
number of unique values = 81018
unique values = ['2017-10-04 19:55:00' '2018-07-26 14:31:00' '2018-08-08 13:50:00' ...
 '2017-08-28 20:52:26' '2018-01-12 15:35:03' '2018-03-09 22:11:59']
# <order_delivered_customer_date>
number of unique values = 95664
unique values = ['2017-10-10 21:25:13' '2018-08-07 15:27:45' '2018-08-17 18:06:29' ...
 '2017-09-21 11:24:17' '2018-01-25 23:32:54' '2018-03-16 13:08:30']
# <order_estimated_delivery_date>
number of unique values = 459
unique values = ['2017-10-18 00:00:00' '2018-08-13 00:00:00' '2018-09-04 00:00:00'
 '2017-12-15 00:00:00' '2018-02-26 00:00:00' '2017-08-01 00:00:00'
 '2017-05-09 00:00:00' '2017-06-07 00:00:00' '2017-03-06 00:00:00'
 '2017-08-23 00:00:00' '2017-08-08 00:00:00' '2018-07-18 00:00:00'
 '2018-08-08 00:00:00' '2018-03-21 00:00:00' '2018-07-04 00:00:00'
 '2018-02-06 00:00:00' '2018-01-29 00:00:00' '2017-12-11 00:00:00'
 '2017-11-23 00:00:00' '2017-09-28 00:00:00' '2018-03-29 00:00:00'
 '2018-02-21 00:00:00' '2018-08-17 00:00:00' '2018-03-12 00:00:00'
 '2018-03-28 00:00:00' '2018-05-23 00:00:00' '2018-04-13 00:00:00'
 '2018-05-15 00:00:00' '2018-01-08 00:00:00' '2018-03-07 00:00:00'
 '2018-08-06 00:00:00' '2018-03-20 00:00:00' '2017-08-22 00:00:00'
 '2018-07-17 00:00:00' '2018-04-12 00:00:00' '2017-06-12 00:00:00'
 '2017-12-21 00:00:00' '2017-09-01 00:00:00' '2018-09-13 00:00:00'
 '2018-06-28 00:00:00' '2017-06-09 00:00:00' '2018-05-25 00:00:00'
 '2017-08-31 00:00:00' '2018-02-23 00:00:00' '2018-07-20 00:00:00'
 '2018-08-16 00:00:00' '2018-01-16 00:00:00' '2017-09-20 00:00:00'
 '2018-07-16 00:00:00' '2018-07-05 00:00:00' '2018-04-02 00:00:00'
 '2017-03-30 00:00:00' '2017-07-06 00:00:00' '2017-12-18 00:00:00'
 '2018-08-15 00:00:00' '2017-12-05 00:00:00' '2018-03-13 00:00:00'
 '2018-02-14 00:00:00' '2018-07-13 00:00:00' '2018-06-26 00:00:00'
 '2018-08-02 00:00:00' '2017-09-25 00:00:00' '2018-05-08 00:00:00'
 '2017-03-21 00:00:00' '2017-05-12 00:00:00' '2017-10-11 00:00:00'
 '2018-08-30 00:00:00' '2017-08-16 00:00:00' '2018-01-19 00:00:00'
 '2017-04-27 00:00:00' '2017-06-01 00:00:00' '2017-05-25 00:00:00'
 '2017-11-21 00:00:00' '2018-01-03 00:00:00' '2017-09-21 00:00:00'
 '2018-06-05 00:00:00' '2018-02-19 00:00:00' '2018-05-16 00:00:00'
 '2017-10-13 00:00:00' '2018-05-21 00:00:00' '2018-01-22 00:00:00'
 '2018-05-07 00:00:00' '2018-08-27 00:00:00' '2018-06-08 00:00:00'
 '2017-04-26 00:00:00' '2018-07-23 00:00:00' '2017-06-06 00:00:00'
 '2018-08-21 00:00:00' '2018-03-26 00:00:00' '2017-03-10 00:00:00'
 '2017-07-25 00:00:00' '2017-10-16 00:00:00' '2017-12-22 00:00:00'
 '2018-09-05 00:00:00' '2018-08-10 00:00:00' '2018-05-29 00:00:00'
 '2017-12-19 00:00:00' '2017-10-17 00:00:00' '2017-07-10 00:00:00'
 '2018-05-04 00:00:00' '2018-05-14 00:00:00' '2017-08-04 00:00:00'
 '2017-10-03 00:00:00' '2017-12-14 00:00:00' '2017-10-31 00:00:00'
 '2018-01-04 00:00:00' '2018-04-20 00:00:00' '2018-03-08 00:00:00'
 '2018-07-30 00:00:00' '2017-04-17 00:00:00' '2017-07-28 00:00:00'
 '2018-06-04 00:00:00' '2018-07-19 00:00:00' '2018-03-16 00:00:00'
 '2018-01-31 00:00:00' '2017-05-29 00:00:00' '2017-12-27 00:00:00'
 '2018-06-12 00:00:00' '2017-12-20 00:00:00' '2018-03-09 00:00:00'
 '2017-06-05 00:00:00' '2018-02-07 00:00:00' '2017-06-08 00:00:00'
 '2017-08-11 00:00:00' '2018-07-27 00:00:00' '2018-07-25 00:00:00'
 '2017-04-11 00:00:00' '2017-11-09 00:00:00' '2018-04-11 00:00:00'
 '2018-07-11 00:00:00' '2017-09-27 00:00:00' '2018-04-26 00:00:00'
 '2018-02-15 00:00:00' '2018-05-02 00:00:00' '2017-10-20 00:00:00'
 '2017-05-15 00:00:00' '2018-02-02 00:00:00' '2017-04-10 00:00:00'
 '2018-08-23 00:00:00' '2017-07-18 00:00:00' '2017-08-07 00:00:00'
 '2017-08-03 00:00:00' '2017-07-14 00:00:00' '2018-06-06 00:00:00'
 '2018-08-09 00:00:00' '2017-08-21 00:00:00' '2018-07-31 00:00:00'
 '2017-03-28 00:00:00' '2018-02-01 00:00:00' '2018-05-03 00:00:00'
 '2017-06-16 00:00:00' '2017-12-26 00:00:00' '2017-06-28 00:00:00'
 '2017-10-04 00:00:00' '2018-05-11 00:00:00' '2017-10-27 00:00:00'
 '2018-03-06 00:00:00' '2017-12-06 00:00:00' '2017-06-26 00:00:00'
 '2018-04-19 00:00:00' '2018-05-28 00:00:00' '2018-05-09 00:00:00'
 '2017-05-11 00:00:00' '2017-12-13 00:00:00' '2018-01-24 00:00:00'
 '2018-03-22 00:00:00' '2018-04-24 00:00:00' '2017-02-13 00:00:00'
 '2017-05-10 00:00:00' '2018-07-12 00:00:00' '2018-04-27 00:00:00'
 '2017-03-16 00:00:00' '2018-03-05 00:00:00' '2017-12-12 00:00:00'
 '2018-02-08 00:00:00' '2017-03-17 00:00:00' '2018-07-24 00:00:00'
 '2017-10-30 00:00:00' '2018-02-22 00:00:00' '2018-05-30 00:00:00'
 '2018-03-23 00:00:00' '2018-04-16 00:00:00' '2018-05-24 00:00:00'
 '2018-04-05 00:00:00' '2018-04-03 00:00:00' '2018-02-20 00:00:00'
 '2017-11-27 00:00:00' '2018-03-01 00:00:00' '2018-08-14 00:00:00'
 '2017-07-19 00:00:00' '2018-04-17 00:00:00' '2018-08-03 00:00:00'
 '2018-04-06 00:00:00' '2018-04-09 00:00:00' '2017-03-02 00:00:00'
 '2017-10-23 00:00:00' '2018-01-02 00:00:00' '2017-06-23 00:00:00'
 '2018-01-30 00:00:00' '2017-09-13 00:00:00' '2018-07-03 00:00:00'
 '2016-12-09 00:00:00' '2017-08-17 00:00:00' '2018-01-05 00:00:00'
 '2018-08-24 00:00:00' '2018-02-05 00:00:00' '2018-05-18 00:00:00'
 '2018-07-26 00:00:00' '2017-09-04 00:00:00' '2018-08-20 00:00:00'
 '2018-09-21 00:00:00' '2018-03-19 00:00:00' '2018-09-12 00:00:00'
 '2018-08-28 00:00:00' '2017-11-08 00:00:00' '2017-05-19 00:00:00'
 '2018-04-25 00:00:00' '2018-01-17 00:00:00' '2017-11-07 00:00:00'
 '2017-11-14 00:00:00' '2017-11-29 00:00:00' '2017-04-03 00:00:00'
 '2017-07-11 00:00:00' '2017-06-29 00:00:00' '2018-06-14 00:00:00'
 '2016-12-07 00:00:00' '2017-04-25 00:00:00' '2017-11-17 00:00:00'
 '2018-08-22 00:00:00' '2017-07-05 00:00:00' '2017-05-18 00:00:00'
 '2017-12-07 00:00:00' '2018-01-12 00:00:00' '2017-05-04 00:00:00'
 '2017-11-06 00:00:00' '2017-09-18 00:00:00' '2017-05-31 00:00:00'
 '2018-01-26 00:00:00' '2018-01-23 00:00:00' '2017-11-03 00:00:00'
 '2017-10-02 00:00:00' '2017-08-14 00:00:00' '2018-09-18 00:00:00'
 '2017-07-04 00:00:00' '2017-08-29 00:00:00' '2017-10-09 00:00:00'
 '2018-04-04 00:00:00' '2017-12-08 00:00:00' '2017-11-01 00:00:00'
 '2018-06-29 00:00:00' '2017-06-27 00:00:00' '2018-03-27 00:00:00'
 '2017-08-28 00:00:00' '2017-03-09 00:00:00' '2017-05-05 00:00:00'
 '2017-03-24 00:00:00' '2018-03-02 00:00:00' '2017-03-23 00:00:00'
 '2017-02-20 00:00:00' '2017-06-14 00:00:00' '2017-12-01 00:00:00'
 '2018-01-09 00:00:00' '2018-04-23 00:00:00' '2017-07-31 00:00:00'
 '2018-06-19 00:00:00' '2017-04-12 00:00:00' '2018-08-31 00:00:00'
 '2017-07-17 00:00:00' '2017-03-14 00:00:00' '2017-09-29 00:00:00'
 '2018-05-22 00:00:00' '2017-10-10 00:00:00' '2017-04-20 00:00:00'
 '2017-03-03 00:00:00' '2017-12-29 00:00:00' '2018-06-07 00:00:00'
 '2018-01-18 00:00:00' '2018-02-09 00:00:00' '2017-05-16 00:00:00'
 '2017-09-08 00:00:00' '2018-06-13 00:00:00' '2018-06-21 00:00:00'
 '2018-02-16 00:00:00' '2017-08-25 00:00:00' '2017-08-15 00:00:00'
 '2017-11-10 00:00:00' '2018-06-20 00:00:00' '2018-06-01 00:00:00'
 '2018-03-15 00:00:00' '2017-12-28 00:00:00' '2017-03-29 00:00:00'
 '2017-11-22 00:00:00' '2018-03-14 00:00:00' '2018-05-17 00:00:00'
 '2017-10-19 00:00:00' '2018-08-01 00:00:00' '2017-05-08 00:00:00'
 '2017-04-24 00:00:00' '2017-03-27 00:00:00' '2017-07-12 00:00:00'
 '2017-07-27 00:00:00' '2018-01-11 00:00:00' '2017-06-02 00:00:00'
 '2017-05-30 00:00:00' '2017-09-05 00:00:00' '2017-03-13 00:00:00'
 '2017-12-04 00:00:00' '2016-11-29 00:00:00' '2017-02-16 00:00:00'
 '2017-10-05 00:00:00' '2017-08-02 00:00:00' '2017-11-16 00:00:00'
 '2018-05-10 00:00:00' '2018-06-11 00:00:00' '2017-06-30 00:00:00'
 '2018-04-10 00:00:00' '2017-09-06 00:00:00' '2017-06-19 00:00:00'
 '2017-11-13 00:00:00' '2017-04-13 00:00:00' '2017-05-02 00:00:00'
 '2018-08-07 00:00:00' '2018-01-15 00:00:00' '2017-04-04 00:00:00'
 '2018-08-29 00:00:00' '2017-04-07 00:00:00' '2018-06-18 00:00:00'
 '2017-08-10 00:00:00' '2017-05-17 00:00:00' '2017-08-09 00:00:00'
 '2017-09-26 00:00:00' '2017-08-30 00:00:00' '2017-04-06 00:00:00'
 '2017-05-26 00:00:00' '2018-09-20 00:00:00' '2017-07-13 00:00:00'
 '2017-06-20 00:00:00' '2017-07-24 00:00:00' '2017-04-05 00:00:00'
 '2018-09-17 00:00:00' '2017-05-23 00:00:00' '2017-11-28 00:00:00'
 '2017-08-18 00:00:00' '2017-05-03 00:00:00' '2017-09-14 00:00:00'
 '2017-11-30 00:00:00' '2017-07-20 00:00:00' '2017-05-24 00:00:00'
 '2017-02-22 00:00:00' '2018-04-30 00:00:00' '2017-10-25 00:00:00'
 '2017-07-03 00:00:00' '2018-09-03 00:00:00' '2017-09-22 00:00:00'
 '2017-03-07 00:00:00' '2017-06-21 00:00:00' '2018-09-14 00:00:00'
 '2017-11-24 00:00:00' '2017-03-22 00:00:00' '2017-02-17 00:00:00'
 '2017-07-21 00:00:00' '2017-08-24 00:00:00' '2017-07-07 00:00:00'
 '2017-09-11 00:00:00' '2017-06-22 00:00:00' '2017-09-12 00:00:00'
 '2017-06-13 00:00:00' '2017-10-24 00:00:00' '2017-10-06 00:00:00'
 '2017-02-24 00:00:00' '2016-11-30 00:00:00' '2017-03-01 00:00:00'
 '2016-12-01 00:00:00' '2017-02-28 00:00:00' '2017-04-19 00:00:00'
 '2018-09-11 00:00:00' '2017-03-20 00:00:00' '2018-04-18 00:00:00'
 '2018-01-10 00:00:00' '2018-10-17 00:00:00' '2018-06-25 00:00:00'
 '2018-09-06 00:00:00' '2018-09-10 00:00:00' '2017-09-15 00:00:00'
 '2017-03-08 00:00:00' '2017-03-31 00:00:00' '2017-10-26 00:00:00'
 '2017-04-18 00:00:00' '2017-09-19 00:00:00' '2018-09-19 00:00:00'
 '2018-09-25 00:00:00' '2018-06-27 00:00:00' '2017-07-26 00:00:00'
 '2017-05-22 00:00:00' '2016-11-16 00:00:00' '2017-02-15 00:00:00'
 '2017-03-15 00:00:00' '2018-09-27 00:00:00' '2016-11-25 00:00:00'
 '2016-10-28 00:00:00' '2016-10-20 00:00:00' '2018-10-02 00:00:00'
 '2016-12-05 00:00:00' '2017-02-01 00:00:00' '2016-12-08 00:00:00'
 '2018-09-28 00:00:00' '2016-11-28 00:00:00' '2018-06-22 00:00:00'
 '2018-10-10 00:00:00' '2017-02-21 00:00:00' '2017-04-28 00:00:00'
 '2017-02-23 00:00:00' '2017-02-07 00:00:00' '2018-07-02 00:00:00'
 '2017-02-27 00:00:00' '2016-11-23 00:00:00' '2016-11-18 00:00:00'
 '2016-12-12 00:00:00' '2016-12-14 00:00:00' '2018-10-01 00:00:00'
 '2018-09-26 00:00:00' '2016-09-30 00:00:00' '2016-12-02 00:00:00'
 '2018-10-15 00:00:00' '2018-09-24 00:00:00' '2017-02-14 00:00:00'
 '2016-11-24 00:00:00' '2018-10-03 00:00:00' '2016-12-06 00:00:00'
 '2017-01-09 00:00:00' '2018-10-04 00:00:00' '2017-04-14 00:00:00'
 '2018-02-13 00:00:00' '2016-11-07 00:00:00' '2016-11-14 00:00:00'
 '2018-10-05 00:00:00' '2016-10-04 00:00:00' '2018-10-16 00:00:00'
 '2016-12-13 00:00:00' '2018-10-11 00:00:00' '2018-10-25 00:00:00'
 '2016-12-16 00:00:00' '2016-11-17 00:00:00' '2016-12-20 00:00:00'
 '2017-01-19 00:00:00' '2017-02-09 00:00:00' '2016-10-24 00:00:00'
 '2016-12-30 00:00:00' '2017-02-10 00:00:00' '2018-07-06 00:00:00'
 '2018-10-30 00:00:00' '2018-10-23 00:00:00' '2018-11-12 00:00:00'
 '2016-12-19 00:00:00' '2016-12-23 00:00:00' '2017-01-11 00:00:00'
 '2016-10-25 00:00:00' '2018-07-10 00:00:00' '2016-10-27 00:00:00']
--------------order_items----------------
# <order_id>
number of unique values = 98666
unique values = ['00010242fe8c5a6d1ba2dd792cb16214' '00018f77f2f0320c557190d7a144bdd3'
 '000229ec398224ef6ca0657da4fc703e' ... 'fffce4705a9662cd70adb13d4a31832d'
 'fffe18544ffabc95dfada21779c9644f' 'fffe41c64501cc87c801fd61db3f6244']
# <order_item_id>

number of unique values = 21
unique values = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
# <product_id>
number of unique values = 32951
unique values = ['4244733e06e7ecb4970a6e2683c13e61' 'e5f2d52b802189ee658865ca93d83a8f'
 'c777355d18b72b67abbeef9df44fd0fd' ... 'dd469c03ad67e201bc2179ef077dcd48'
 'bbe7651fef80287a816ead73f065fc4b' '350688d9dc1e75ff97be326363655e01']
# <seller_id>
number of unique values = 3095
unique values = ['48436dade18ac8b2bce089ec2a041202' 'dd7ddc04e1b6c2c614352b383efe2d36'
 '5b51032eddd242adc84c38acab88f23d' ... '3fefda3299e6dfaea3466ef346a3571a'
 '80ceebb4ee9b31afb6c6a916a574a1e2' '3e35a8bb43569389d3cebef0ce820f69']
# <shipping_limit_date>
number of unique values = 93318
unique values = ['2017-09-19 09:45:35' '2017-05-03 11:05:13' '2018-01-18 14:48:30' ...
 '2017-10-30 17:14:25' '2017-08-21 00:04:32' '2018-06-12 17:10:13']
# <price>
number of unique values = 5968
unique values = [ 58.9  239.9  199.   ...   7.84 399.85 736.  ]
# <freight_value>
number of unique values = 6999
unique values = [ 13.29  19.93  17.87 ... 127.55   6.79   6.37]
--------------order_payments----------------
# <order_id>
number of unique values = 99440
unique values = ['b81ef226f3fe1789b1e8b2acac839d17' 'a9810da82917af2d9aefd1278f1dcfa0'
 '25e8ea4e93396b6fa0d3dd708e76c1bd' ... '32609bbb3dd69b3c066a6860554a77bf'
 'b8b61059626efa996a60be9bb9320e10' '28bbae6599b09d39ca406b747b6632b1']
# <payment_sequential>
number of unique values = 29
unique values = [ 1  2  4  5  3  8  6  7 10 11 17 19 27 12  9 15 13 14 16 25 22 26 29 28
 18 21 24 23 20]
# <payment_type>
number of unique values = 5
unique values = ['credit_card' 'boleto' 'voucher' 'debit_card' 'not_defined']
# <payment_installments>
number of unique values = 24
unique values = [ 8  1  2  3  6  5  4 10  7 12  9 13 15 24 11 18 14 20 21 17 22  0 16 23]
# <payment_value>
number of unique values = 29077
unique values = [ 99.33  24.39  65.71 ... 205.71 100.55 363.31]
--------------order_reviews----------------
# <review_id>
number of unique values = 99173
unique values = ['7bc2406110b926393aa56f80a40eba40' '80e641a11e56f04c1ad469d5645fdfde'
 '228ce5500dc1d8e020d8d1322874b6f0' ... '1adeb9d84d72fe4e337617733eb85149'
 'be360f18f5df1e0541061c87021e6d93' 'efe49f1d6f951dd88b51e6ccd4cc548f']
# <order_id>
number of unique values = 99441
unique values = ['73fc7af87114b39712e6da79b0a377eb' 'a548910a1c6147796b98fdf73dbeba33'
 'f9e4b658b201a9f2ecdecbb34bed034b' ... '7725825d039fc1f0ceb7635e3f7d9206'
 'f8bd3f2000c28c5342fedeb5e50f2e75' '90531360ecb1eec2a1fbb265a0db0508']
# <review_score>
number of unique values = 5
unique values = [4 5 1 3 2]
# <review_comment_title>
number of unique values = 4600
unique values = [nan 'recomendo' 'Super recomendo' ... 'Não foi entregue o pedido'
 'OTIMA EMBALAGEM' 'Foto enganosa ']
# <review_comment_message>
number of unique values = 36921
unique values = [nan 'Recebi bem antes do prazo estipulado.'
 'Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa'
 ... 'Excelente mochila, entrega super rápida. Super recomendo essa loja!'
 'Solicitei a compra de uma capa de retrovisor celta/prisma/meriva - preta - lado esquerdo, mas chegou para mim uma capa do lado direito de outro modelo de carro.\r\nEstou decepcionado! Fico no aguardo!'
 'meu produto chegou e ja tenho que devolver, pois está com defeito , não segurar carga']
# <review_creation_date>
number of unique values = 637
unique values = ['2018-01-18 00:00:00' '2018-03-10 00:00:00' '2018-02-17 00:00:00'
 '2017-04-21 00:00:00' '2018-03-01 00:00:00' '2018-04-13 00:00:00'
 '2017-07-16 00:00:00' '2018-08-14 00:00:00' '2017-05-17 00:00:00'
 '2018-05-22 00:00:00' '2017-12-23 00:00:00' '2017-12-19 00:00:00'
 '2018-02-16 00:00:00' '2018-03-28 00:00:00' '2017-04-30 00:00:00'
 '2018-05-23 00:00:00' '2018-03-24 00:00:00' '2017-09-29 00:00:00'
 '2018-08-15 00:00:00' '2017-10-06 00:00:00' '2018-03-17 00:00:00'
 '2018-07-10 00:00:00' '2017-09-09 00:00:00' '2017-12-01 00:00:00'
 '2017-06-23 00:00:00' '2017-11-01 00:00:00' '2018-03-23 00:00:00'
 '2018-03-29 00:00:00' '2017-12-13 00:00:00' '2017-07-19 00:00:00'
 '2018-04-08 00:00:00' '2018-08-25 00:00:00' '2018-06-07 00:00:00'
 '2017-09-12 00:00:00' '2018-06-13 00:00:00' '2018-03-22 00:00:00'
 '2018-08-10 00:00:00' '2018-05-13 00:00:00' '2018-02-08 00:00:00'
 '2017-12-05 00:00:00' '2018-03-11 00:00:00' '2018-01-25 00:00:00'
 '2017-05-13 00:00:00' '2017-09-22 00:00:00' '2018-04-24 00:00:00'
 '2017-05-19 00:00:00' '2018-01-28 00:00:00' '2018-07-14 00:00:00'
 '2018-06-02 00:00:00' '2017-12-15 00:00:00' '2017-03-21 00:00:00'
 '2018-05-10 00:00:00' '2017-10-27 00:00:00' '2018-05-31 00:00:00'
 '2018-07-25 00:00:00' '2018-04-03 00:00:00' '2017-06-02 00:00:00'
 '2018-04-18 00:00:00' '2018-02-20 00:00:00' '2018-04-04 00:00:00'
 '2018-02-27 00:00:00' '2018-06-03 00:00:00' '2018-08-17 00:00:00'
 '2016-12-09 00:00:00' '2017-08-09 00:00:00' '2018-04-10 00:00:00'
 '2018-01-31 00:00:00' '2017-11-09 00:00:00' '2018-08-28 00:00:00'
 '2018-07-03 00:00:00' '2017-07-29 00:00:00' '2018-06-14 00:00:00'
 '2018-06-19 00:00:00' '2018-01-12 00:00:00' '2018-04-06 00:00:00'
 '2017-03-31 00:00:00' '2018-02-23 00:00:00' '2018-05-15 00:00:00'
 '2017-03-23 00:00:00' '2018-01-04 00:00:00' '2018-03-08 00:00:00'
 '2018-03-07 00:00:00' '2017-08-03 00:00:00' '2017-12-12 00:00:00'
 '2017-07-12 00:00:00' '2017-10-31 00:00:00' '2017-11-22 00:00:00'
 '2017-06-24 00:00:00' '2018-06-21 00:00:00' '2018-04-22 00:00:00'
 '2018-01-30 00:00:00' '2018-01-16 00:00:00' '2017-12-17 00:00:00'
 '2017-10-24 00:00:00' '2018-08-02 00:00:00' '2018-03-16 00:00:00'
 '2017-08-29 00:00:00' '2017-10-26 00:00:00' '2018-01-10 00:00:00'
 '2017-11-07 00:00:00' '2018-06-26 00:00:00' '2017-12-16 00:00:00'
 '2017-11-23 00:00:00' '2018-07-13 00:00:00' '2017-07-27 00:00:00'
 '2017-09-14 00:00:00' '2017-12-27 00:00:00' '2018-01-20 00:00:00'
 '2017-09-17 00:00:00' '2016-10-22 00:00:00' '2017-10-10 00:00:00'
 '2017-09-24 00:00:00' '2017-06-22 00:00:00' '2018-04-12 00:00:00'
 '2018-08-26 00:00:00' '2018-02-01 00:00:00' '2018-04-05 00:00:00'
 '2018-03-09 00:00:00' '2018-04-19 00:00:00' '2017-06-03 00:00:00'
 '2017-05-30 00:00:00' '2017-08-22 00:00:00' '2018-05-16 00:00:00'
 '2017-11-15 00:00:00' '2017-08-18 00:00:00' '2018-03-14 00:00:00'
 '2017-01-31 00:00:00' '2017-11-02 00:00:00' '2018-06-22 00:00:00'
 '2018-04-28 00:00:00' '2017-10-02 00:00:00' '2017-12-29 00:00:00'
 '2017-12-20 00:00:00' '2017-11-19 00:00:00' '2017-12-02 00:00:00'
 '2018-04-27 00:00:00' '2018-08-04 00:00:00' '2018-08-21 00:00:00'
 '2018-05-11 00:00:00' '2017-04-06 00:00:00' '2018-07-22 00:00:00'
 '2017-08-08 00:00:00' '2017-07-25 00:00:00' '2018-05-05 00:00:00'
 '2017-05-31 00:00:00' '2018-05-12 00:00:00' '2018-07-12 00:00:00'
 '2018-07-04 00:00:00' '2017-05-06 00:00:00' '2018-08-30 00:00:00'
 '2018-07-07 00:00:00' '2018-07-27 00:00:00' '2017-09-06 00:00:00'
 '2018-06-28 00:00:00' '2016-10-19 00:00:00' '2018-03-25 00:00:00'
 '2018-05-08 00:00:00' '2017-05-20 00:00:00' '2017-04-14 00:00:00'
 '2017-02-24 00:00:00' '2018-03-27 00:00:00' '2018-06-06 00:00:00'
 '2018-05-24 00:00:00' '2018-01-23 00:00:00' '2018-07-11 00:00:00'
 '2018-05-26 00:00:00' '2017-12-22 00:00:00' '2018-02-24 00:00:00'
 '2017-05-14 00:00:00' '2017-08-26 00:00:00' '2018-08-22 00:00:00'
 '2017-08-31 00:00:00' '2017-09-20 00:00:00' '2018-08-11 00:00:00'
 '2018-01-17 00:00:00' '2017-10-17 00:00:00' '2018-04-21 00:00:00'
 '2017-09-07 00:00:00' '2016-11-02 00:00:00' '2018-08-08 00:00:00'
 '2018-08-03 00:00:00' '2017-06-07 00:00:00' '2018-07-24 00:00:00'
 '2018-08-24 00:00:00' '2018-08-23 00:00:00' '2017-10-08 00:00:00'
 '2018-06-12 00:00:00' '2017-09-23 00:00:00' '2017-07-05 00:00:00'
 '2018-02-25 00:00:00' '2017-11-24 00:00:00' '2018-06-24 00:00:00'
 '2018-04-17 00:00:00' '2018-02-09 00:00:00' '2017-03-22 00:00:00'
 '2018-08-29 00:00:00' '2017-10-22 00:00:00' '2018-08-05 00:00:00'
 '2018-02-28 00:00:00' '2018-06-08 00:00:00' '2018-08-01 00:00:00'
 '2018-06-11 00:00:00' '2018-06-30 00:00:00' '2018-08-07 00:00:00'
 '2017-07-26 00:00:00' '2017-07-08 00:00:00' '2018-05-25 00:00:00'
 '2018-03-06 00:00:00' '2017-09-26 00:00:00' '2018-05-19 00:00:00'
 '2017-05-16 00:00:00' '2017-12-30 00:00:00' '2017-11-29 00:00:00'
 '2017-12-28 00:00:00' '2017-12-09 00:00:00' '2018-03-30 00:00:00'
 '2018-01-05 00:00:00' '2018-02-02 00:00:00' '2018-03-20 00:00:00'
 '2017-10-20 00:00:00' '2018-08-12 00:00:00' '2017-10-03 00:00:00'
 '2017-09-19 00:00:00' '2018-03-31 00:00:00' '2018-08-18 00:00:00'
 '2017-11-10 00:00:00' '2018-07-06 00:00:00' '2018-04-11 00:00:00'
 '2018-03-04 00:00:00' '2017-05-08 00:00:00' '2017-10-21 00:00:00'
 '2017-04-20 00:00:00' '2018-02-06 00:00:00' '2018-01-13 00:00:00'
 '2017-09-01 00:00:00' '2017-07-13 00:00:00' '2017-05-27 00:00:00'
 '2017-03-08 00:00:00' '2017-10-14 00:00:00' '2018-03-21 00:00:00'
 '2017-09-21 00:00:00' '2018-03-18 00:00:00' '2017-03-15 00:00:00'
 '2018-07-01 00:00:00' '2018-01-09 00:00:00' '2017-09-27 00:00:00'
 '2018-06-20 00:00:00' '2017-10-29 00:00:00' '2017-07-21 00:00:00'
 '2017-09-05 00:00:00' '2018-04-26 00:00:00' '2017-11-14 00:00:00'
 '2017-11-25 00:00:00' '2018-05-07 00:00:00' '2017-04-05 00:00:00'
 '2017-11-05 00:00:00' '2017-08-17 00:00:00' '2017-10-07 00:00:00'
 '2017-07-11 00:00:00' '2017-05-24 00:00:00' '2017-01-27 00:00:00'
 '2018-08-16 00:00:00' '2018-07-31 00:00:00' '2017-03-04 00:00:00'
 '2017-12-07 00:00:00' '2017-08-12 00:00:00' '2017-10-15 01:00:00'
 '2017-11-04 00:00:00' '2017-12-06 00:00:00' '2017-03-29 00:00:00'
 '2018-05-01 00:00:00' '2017-06-09 00:00:00' '2017-06-15 00:00:00'
 '2017-06-14 00:00:00' '2017-05-03 00:00:00' '2018-03-19 00:00:00'
 '2018-04-20 00:00:00' '2017-05-12 00:00:00' '2018-05-04 00:00:00'
 '2018-02-04 00:00:00' '2017-08-02 00:00:00' '2018-08-09 00:00:00'
 '2017-08-19 00:00:00' '2017-04-11 00:00:00' '2017-05-23 00:00:00'
 '2018-01-26 00:00:00' '2018-06-17 00:00:00' '2018-02-22 00:00:00'
 '2018-03-26 00:00:00' '2017-05-04 00:00:00' '2017-03-19 00:00:00'
 '2017-05-10 00:00:00' '2017-04-12 00:00:00' '2018-03-03 00:00:00'
 '2018-01-11 00:00:00' '2018-01-06 00:00:00' '2018-07-29 00:00:00'
 '2017-09-30 00:00:00' '2018-06-05 00:00:00' '2017-12-08 00:00:00'
 '2018-07-21 00:00:00' '2017-02-17 00:00:00' '2017-12-31 00:00:00'
 '2017-06-17 00:00:00' '2017-07-18 00:00:00' '2017-08-10 00:00:00'
 '2018-04-25 00:00:00' '2017-10-25 00:00:00' '2017-12-14 00:00:00'
 '2017-05-18 00:00:00' '2018-05-20 00:00:00' '2018-05-18 00:00:00'
 '2018-04-07 00:00:00' '2018-04-14 00:00:00' '2018-02-10 00:00:00'
 '2018-01-24 00:00:00' '2018-05-03 00:00:00' '2017-05-26 00:00:00'
 '2017-06-21 00:00:00' '2018-02-15 00:00:00' '2018-01-19 00:00:00'
 '2017-10-28 00:00:00' '2018-03-15 00:00:00' '2017-07-01 00:00:00'
 '2017-03-09 00:00:00' '2018-07-05 00:00:00' '2018-02-03 00:00:00'
 '2017-07-22 00:00:00' '2016-10-20 00:00:00' '2017-11-18 00:00:00'
 '2017-02-21 00:00:00' '2017-10-01 00:00:00' '2017-05-25 00:00:00'
 '2018-03-02 00:00:00' '2017-07-04 00:00:00' '2017-03-14 00:00:00'
 '2018-07-26 00:00:00' '2017-09-03 00:00:00' '2018-06-09 00:00:00'
 '2017-09-28 00:00:00' '2017-02-25 00:00:00' '2017-11-28 00:00:00'
 '2017-10-04 00:00:00' '2018-06-04 00:00:00' '2018-04-15 00:00:00'
 '2018-02-18 00:00:00' '2017-06-06 00:00:00' '2018-05-30 00:00:00'
 '2018-01-07 00:00:00' '2017-07-07 00:00:00' '2017-02-23 00:00:00'
 '2017-02-03 00:00:00' '2018-05-09 00:00:00' '2018-07-28 00:00:00'
 '2017-11-26 00:00:00' '2018-06-27 00:00:00' '2017-09-25 00:00:00'
 '2017-07-20 00:00:00' '2018-05-27 00:00:00' '2017-11-12 00:00:00'
 '2018-06-29 00:00:00' '2017-03-03 00:00:00' '2017-11-17 00:00:00'
 '2017-08-20 00:00:00' '2017-12-24 00:00:00' '2018-06-23 00:00:00'
 '2018-06-16 00:00:00' '2017-08-25 00:00:00' '2017-07-14 00:00:00'
 '2018-08-31 00:00:00' '2017-03-10 00:00:00' '2017-04-22 00:00:00'
 '2017-10-11 00:00:00' '2017-05-01 00:00:00' '2017-04-29 00:00:00'
 '2017-04-13 00:00:00' '2018-02-19 00:00:00' '2017-02-11 00:00:00'
 '2017-03-07 00:00:00' '2017-11-08 00:00:00' '2017-10-13 00:00:00'
 '2018-04-29 00:00:00' '2017-08-11 00:00:00' '2017-12-21 00:00:00'
 '2017-04-18 00:00:00' '2017-03-30 00:00:00' '2017-12-10 00:00:00'
 '2018-06-15 00:00:00' '2018-03-13 00:00:00' '2018-01-27 00:00:00'
 '2017-02-02 00:00:00' '2017-08-30 00:00:00' '2017-03-11 00:00:00'
 '2017-08-04 00:00:00' '2017-07-15 00:00:00' '2017-05-07 00:00:00'
 '2017-08-24 00:00:00' '2017-06-10 00:00:00' '2018-06-10 00:00:00'
 '2017-02-22 00:00:00' '2018-05-06 00:00:00' '2017-01-26 00:00:00'
 '2017-03-24 00:00:00' '2017-10-30 00:00:00' '2017-07-30 00:00:00'
 '2017-08-15 00:00:00' '2017-03-12 00:00:00' '2016-10-28 00:00:00'
 '2017-08-06 00:00:00' '2017-05-11 00:00:00' '2017-06-20 00:00:00'
 '2018-02-07 00:00:00' '2017-10-18 00:00:00' '2017-06-18 00:00:00'
 '2018-01-21 00:00:00' '2017-09-08 00:00:00' '2017-11-30 00:00:00'
 '2018-01-01 00:00:00' '2017-08-23 00:00:00' '2018-07-08 00:00:00'
 '2017-04-28 00:00:00' '2017-02-08 00:00:00' '2017-06-16 00:00:00'
 '2017-11-11 00:00:00' '2017-10-09 00:00:00' '2018-01-08 00:00:00'
 '2017-10-12 00:00:00' '2017-08-01 00:00:00' '2017-05-05 00:00:00'
 '2017-08-27 00:00:00' '2018-01-14 00:00:00' '2017-06-30 00:00:00'
 '2017-09-15 00:00:00' '2017-04-01 00:00:00' '2017-04-10 00:00:00'
 '2017-10-05 00:00:00' '2017-08-16 00:00:00' '2017-01-24 00:00:00'
 '2018-08-19 00:00:00' '2017-04-04 00:00:00' '2017-06-08 00:00:00'
 '2017-02-09 00:00:00' '2017-02-15 00:00:00' '2017-02-16 00:00:00'
 '2018-02-12 00:00:00' '2017-03-16 00:00:00' '2017-06-11 00:00:00'
 '2017-03-18 00:00:00' '2018-06-01 00:00:00' '2017-03-02 00:00:00'
 '2017-07-28 00:00:00' '2018-05-17 00:00:00' '2017-02-20 00:00:00'
 '2017-06-01 00:00:00' '2017-06-27 00:00:00' '2017-06-13 00:00:00'
 '2017-09-10 00:00:00' '2017-07-06 00:00:00' '2017-04-19 00:00:00'
 '2017-05-28 00:00:00' '2017-10-19 00:00:00' '2017-04-23 00:00:00'
 '2018-01-22 00:00:00' '2017-08-13 00:00:00' '2018-02-21 00:00:00'
 '2017-02-10 00:00:00' '2017-03-25 00:00:00' '2017-06-28 00:00:00'
 '2018-02-26 00:00:00' '2017-03-17 00:00:00' '2017-12-03 00:00:00'
 '2017-09-13 00:00:00' '2017-12-11 00:00:00' '2017-08-05 00:00:00'
 '2017-02-12 00:00:00' '2017-07-31 00:00:00' '2016-11-01 00:00:00'
 '2017-11-03 00:00:00' '2017-06-29 00:00:00' '2018-01-15 00:00:00'
 '2017-11-16 00:00:00' '2017-12-18 00:00:00' '2018-05-29 00:00:00'
 '2017-01-25 00:00:00' '2017-06-04 00:00:00' '2018-05-02 00:00:00'
 '2017-03-28 00:00:00' '2018-04-09 00:00:00' '2017-04-08 00:00:00'
 '2017-08-14 00:00:00' '2017-02-26 00:00:00' '2017-09-02 00:00:00'
 '2017-07-17 00:00:00' '2017-01-29 00:00:00' '2017-02-19 00:00:00'
 '2017-07-03 00:00:00' '2017-03-26 00:00:00' '2017-11-21 00:00:00'
 '2017-05-09 00:00:00' '2016-10-26 00:00:00' '2017-01-18 00:00:00'
 '2018-07-17 00:00:00' '2018-07-15 00:00:00' '2017-02-18 00:00:00'
 '2017-02-04 00:00:00' '2017-04-02 00:00:00' '2018-07-18 00:00:00'
 '2017-09-16 00:00:00' '2016-11-19 00:00:00' '2018-03-12 00:00:00'
 '2017-04-07 00:00:00' '2017-12-04 00:00:00' '2017-07-23 00:00:00'
 '2018-04-16 00:00:00' '2018-06-25 00:00:00' '2018-02-11 00:00:00'
 '2018-05-21 00:00:00' '2017-01-17 00:00:00' '2017-05-29 00:00:00'
 '2017-01-28 00:00:00' '2018-04-01 00:00:00' '2017-02-07 00:00:00'
 '2017-05-21 00:00:00' '2018-01-03 00:00:00' '2016-10-21 00:00:00'
 '2016-10-27 00:00:00' '2017-06-26 00:00:00' '2017-11-13 00:00:00'
 '2018-07-30 00:00:00' '2017-07-24 00:00:00' '2017-06-25 00:00:00'
 '2017-03-01 00:00:00' '2016-10-25 00:00:00' '2016-10-09 00:00:00'
 '2017-06-12 00:00:00' '2017-02-14 00:00:00' '2018-08-13 00:00:00'
 '2017-02-01 00:00:00' '2017-01-19 00:00:00' '2017-11-20 00:00:00'
 '2017-04-24 00:00:00' '2018-07-09 00:00:00' '2017-03-05 00:00:00'
 '2016-12-03 00:00:00' '2017-04-09 00:00:00' '2016-11-08 00:00:00'
 '2018-08-06 00:00:00' '2016-11-26 00:00:00' '2017-10-23 00:00:00'
 '2016-12-01 00:00:00' '2017-07-10 00:00:00' '2017-07-02 00:00:00'
 '2017-07-09 00:00:00' '2016-10-18 00:00:00' '2017-12-25 00:00:00'
 '2016-11-04 00:00:00' '2016-10-29 00:00:00' '2018-04-30 00:00:00'
 '2017-02-13 00:00:00' '2016-11-09 00:00:00' '2016-11-18 00:00:00'
 '2016-12-16 00:00:00' '2018-03-05 00:00:00' '2017-02-05 00:00:00'
 '2018-04-02 00:00:00' '2016-11-30 00:00:00' '2017-09-04 00:00:00'
 '2017-05-22 00:00:00' '2017-09-18 00:00:00' '2017-10-16 00:00:00'
 '2016-11-23 00:00:00' '2018-02-05 00:00:00' '2016-12-15 00:00:00'
 '2017-05-02 00:00:00' '2016-11-05 00:00:00' '2016-11-17 00:00:00'
 '2016-11-06 00:00:00' '2017-08-28 00:00:00' '2016-12-07 00:00:00'
 '2017-04-03 00:00:00' '2017-11-27 00:00:00' '2016-12-04 00:00:00'
 '2016-10-30 00:00:00' '2018-07-02 00:00:00' '2017-04-15 00:00:00'
 '2016-11-11 00:00:00' '2018-04-23 00:00:00' '2018-07-19 00:00:00'
 '2016-11-27 00:00:00' '2016-11-25 00:00:00' '2017-01-21 00:00:00'
 '2016-11-20 00:00:00' '2018-01-29 00:00:00' '2018-06-18 00:00:00'
 '2018-05-28 00:00:00' '2018-08-27 00:00:00' '2016-12-29 00:00:00'
 '2018-05-14 00:00:00' '2016-12-25 00:00:00' '2017-04-16 00:00:00'
 '2016-11-10 00:00:00' '2018-08-20 00:00:00' '2018-07-16 00:00:00'
 '2016-10-16 01:00:00' '2016-10-23 00:00:00' '2017-03-06 00:00:00'
 '2017-03-27 00:00:00' '2017-01-20 00:00:00' '2017-06-19 00:00:00'
 '2016-12-08 00:00:00' '2018-07-20 00:00:00' '2016-10-06 00:00:00'
 '2018-07-23 00:00:00' '2017-01-14 00:00:00' '2016-10-15 00:00:00'
 '2017-01-12 00:00:00' '2016-12-02 00:00:00' '2016-10-24 00:00:00'
 '2017-08-21 00:00:00' '2018-01-02 00:00:00' '2016-12-14 00:00:00'
 '2017-01-13 00:00:00' '2017-09-11 00:00:00' '2017-02-06 00:00:00'
 '2016-10-31 00:00:00' '2016-12-11 00:00:00' '2017-03-20 00:00:00'
 '2017-05-15 00:00:00' '2016-11-29 00:00:00' '2016-12-10 00:00:00'
 '2016-10-02 00:00:00' '2017-01-22 00:00:00' '2017-03-13 00:00:00'
 '2018-02-13 00:00:00' '2016-11-15 00:00:00' '2017-06-05 00:00:00'
 '2017-01-04 00:00:00']
# <review_answer_timestamp>

number of unique values = 99010
unique values = ['2018-01-18 21:46:59' '2018-03-11 03:05:13' '2018-02-18 14:36:24' ...
 '2018-07-02 12:59:13' '2017-12-16 01:29:43' '2017-07-03 21:01:49']
--------------products----------------
# <product_id>
number of unique values = 32951
unique values = ['1e9e8ef04dbcff4541ed26657ea517e5' '3aa071139cb16b67ca9e5dea641aaa2f'
 '96bd76ec8810374ed1b65e291975717f' ... '9a7c6041fa9592d9d9ef6cfe62a71f8c'
 '83808703fc0706a22e264b9d75f04a2e' '106392145fca363410d287a815be6de4']
# <product_category_name>
number of unique values = 73
unique values = ['perfumaria' 'artes' 'esporte_lazer' 'bebes' 'utilidades_domesticas'
 'instrumentos_musicais' 'cool_stuff' 'moveis_decoracao'
 'eletrodomesticos' 'brinquedos' 'cama_mesa_banho'
 'construcao_ferramentas_seguranca' 'informatica_acessorios'
 'beleza_saude' 'malas_acessorios' 'ferramentas_jardim'
 'moveis_escritorio' 'automotivo' 'eletronicos' 'fashion_calcados'
 'telefonia' 'papelaria' 'fashion_bolsas_e_acessorios' 'pcs'
 'casa_construcao' 'relogios_presentes'
 'construcao_ferramentas_construcao' 'pet_shop' 'eletroportateis'
 'agro_industria_e_comercio' nan 'moveis_sala' 'sinalizacao_e_seguranca'
 'climatizacao' 'consoles_games' 'livros_interesse_geral'
 'construcao_ferramentas_ferramentas' 'fashion_underwear_e_moda_praia'
 'fashion_roupa_masculina'
 'moveis_cozinha_area_de_servico_jantar_e_jardim'
 'industria_comercio_e_negocios' 'telefonia_fixa'
 'construcao_ferramentas_iluminacao' 'livros_tecnicos'
 'eletrodomesticos_2' 'artigos_de_festas' 'bebidas' 'market_place'
 'la_cuisine' 'construcao_ferramentas_jardim' 'fashion_roupa_feminina'
 'casa_conforto' 'audio' 'alimentos_bebidas' 'musica' 'alimentos'
 'tablets_impressao_imagem' 'livros_importados'
 'portateis_casa_forno_e_cafe' 'fashion_esporte' 'artigos_de_natal'
 'fashion_roupa_infanto_juvenil' 'dvds_blu_ray' 'artes_e_artesanato'
 'pc_gamer' 'moveis_quarto' 'cine_foto' 'fraldas_higiene' 'flores'
 'casa_conforto_2' 'portateis_cozinha_e_preparadores_de_alimentos'
 'seguros_e_servicos' 'moveis_colchao_e_estofado' 'cds_dvds_musicais']
# <product_name_lenght>
number of unique values = 66
unique values = [40. 44. 46. 27. 37. 60. 56. 57. 36. 54. 49. 43. 51. 59. 22. 39. 52. 58.
 55. 35. 50. 45. 31. 47. 63. 33. 38. 20. 42. 53. 41. nan 30. 34. 48. 29.
 32. 25. 23. 64. 28. 19. 61. 21. 62. 18. 17. 24. 26. 15. 16. 10. 14. 69.
  9. 13. 12. 11.  7.  8. 68.  5. 66. 72. 67. 76.  6.]
# <product_description_lenght>
number of unique values = 2960
unique values = [ 287.  276.  250. ... 2836. 3364. 2207.]
# <product_photos_qty>
number of unique values = 19
unique values = [ 1.  4.  2.  3.  5.  9.  6. nan  7. 12. 10. 11. 17.  8. 15. 13. 14. 20.
 18. 19.]
# <product_weight_g>
number of unique values = 2204
unique values = [ 225. 1000.  154. ... 1206.  934. 1920.]
# <product_length_cm>
number of unique values = 99
unique values = [ 16.  30.  18.  26.  20.  38.  70.  40.  27.  17.  50.  68. 100.  29.
  36.  21.  35.  42.  23.  62.  52.  34.  33.  87.  19.  25.  49.  22.
  45.  47.  69.  60.  41.  32.  24.  44.  63.  55. 105.  53.  75.  43.
  37.  80.  39.  65.  58.  56.  46.  84.  57.  61.  71.  31.  85.  13.
  28.  66.  78.  51.  76.  48.  88.  83.  95. 102.  92.  59.  14.   8.
  11.  82.  67.  54.  15.  98.  64.  79.  90.  72.  93. 103.  74.  77.
  12.  81.  94. 101.  86. 104.   9.  89.  91.  99.  97.  nan  10.  96.
  73.   7.]
# <product_height_cm>
number of unique values = 102
unique values = [ 10.  18.   9.   4.  17.   5.  24.   8.  13.  19.   7.  11.   2.  15.
  25.  23.  51.  30.   3.  12.  20.  40.  32.  16.  28.  14.  50.  21.
  66.  22.   6.  26.  70.  60.  63.  44.  36.  34.  81.  35.  88.  33.
  61.  27.  45. 102.  43.  48.  55.  41.  29.  31.  37.  65. 103.  52.
  53.  69.  82. 100.  49.  74.  54.  57.  42.  93.  39.  38.  47.  80.
  62. 105.  64.  78.  72.  90.  46.  77.  96.  73.  67.  58. 104.  71.
  79.  75.  85.  68.  56.  83.  84.  86.  59.  76.  87.  nan  99.  95.
  89.  92.  94.  98.  97.]
# <product_width_cm>
number of unique values = 95
unique values = [ 14.  20.  15.  26.  13.  11.  44.  40.  17.  12.  16.  45.  30.  50.
  23.  34.  31.  42.  25.  41.  35.  79.  38.  47.  24.  49.  37.  39.
  53.  27.  18.  56.  70.  33.  55.  22.  32.  46.  19.  28.  43.  58.
  36.  21.  67.  48. 105.  51.  60.  29.  52.  59.  71.  68.  65.   6.
   8.  10.  54.  57.  74.  92.  82.  61.  76.  63.  93.  73.  80.  87.
  78.  83.   9.  84.  91.  69.  64.  90.  62.  85.  66.  75. 100.  nan
 102.  95.  72.  98.  86.   7. 103. 101. 118.  97.  77. 104.]
--------------sellers----------------
# <seller_id>
number of unique values = 3095
unique values = ['3442f8959a84dea7ee197c632cb2df15' 'd1b65fc7debc3361ea86b5f14c68d2e2'
 'ce3ad9de960102d0677a81f5d0bb7b2d' ... '74871d19219c7d518d0090283e03c137'
 'e603cf3fec55f8697c9059638d6c8eb5' '9e25199f6ef7e7c347120ff175652c3b']
# <seller_zip_code_prefix>
number of unique values = 2246
unique values = ['13023' '13844' '20031' ... '04650' '96080' '12051']
# <seller_city>
number of unique values = 611
unique values = ['campinas' 'mogi guacu' 'rio de janeiro' 'sao paulo' 'braganca paulista'
 'brejao' 'penapolis' 'curitiba' 'anapolis' 'itirapina' 'tubarao'
 'lauro de freitas' 'imbituba' 'brasilia' 'porto seguro' 'guaruja'
 'tabatinga' 'salto' 'tres de maio' 'belo horizonte' 'arapongas'
 'sao bernardo do campo' 'tatui' 'garopaba' 'camanducaia' 'tupa'
 'guarulhos' 'sao jose dos pinhais' 'sao ludgero' 'sao jose' 'piracicaba'
 'porto alegre' 'congonhal' 'santo andre' 'osasco' 'valinhos' 'joinville'
 'saquarema' 'barra velha' 'petropolis' 'santo antonio da patrulha'
 'ponta grossa' 'santana de parnaiba' 'sao carlos' 'ibitinga' 'barueri'
 'caxias do sul' 'araguari' 'contagem' 'jaragua do sul' 'lages - sc'
 'bento goncalves' 'catanduva' 'ribeirao pires' 'jaboticabal' 'echapora'
 'cotia' 'rio do sul' 'sorocaba' 'pradopolis' 'itaborai' 'mirassol'
 'birigui' 'assis' 'jaguariuna' 'araraquara' 'macae' 'rio claro'
 'londrina' 'ribeirao preto' 'tres coracoes' 'nhandeara' 'orleans'
 'cuiaba' 'formosa do oeste' 'santos' 'santa terezinha de goias'
 'arvorezinha' 'guiricema' 'caruaru' 'franca' 'salvador' 'diadema'
 'itaquaquecetuba' 'lencois paulista' 'carapicuiba' 'uruacu' 'itajai'
 'loanda' 'maringa' 'ferraz de vasconcelos' 'limeira' 'claudio' 'niteroi'
 'osvaldo cruz' 'sao goncalo' 'jaciara' 'balenario camboriu' 'timbo'
 'jacutinga' 'fortaleza' 'ferraz de  vasconcelos' 'mirandopolis' 'bauru'
 'jacarei' 'itu' 'laranjeiras do sul' 'videira' 'florianopolis'
 'itapecerica da serra' 'mamanguape' 'ponte nova' 'goioere' 'pederneiras'
 'itapevi' 'goiania' 'campina grande' 'estancia velha' 'resende' 'maua'
 'caratinga' 'auriflama/sp' 'cafelandia' 'uba' 'sao paulo / sao paulo'
 'sao jose do rio preto' 'porto ferreira' 'tres coroas' 'blumenau'
 'mogi das cruzes' 'jaci' 'laranjal paulista' 'americana' 'sertanopolis'
 'apucarana' 'colombo' 'vicente de carvalho' 'mesquita' 'sao pauo'
 'cascavel' 'fazenda rio grande' 'taboao da serra' 'sao jose dos campos'
 'toledo' 'marechal candido rondon' 'jundiai' 'mandirituba' 'suzano'
 'vespasiano' 'santa rosa' 'sao joaquim da barra' 'santo antonio de posse'
 'uruguaiana' 'campanha' 'piracanjuba' 'concordia' 'santa rita do sapucai'
 'barretos' 'indaiatuba' 'nilopolis' 'pompeia' 'barro alto' 'são paulo'
 'praia grande' 'luiz alves' 'brusque' 'criciuma' 'jales' 'atibaia'
 'rio branco' 'barra mansa' 'marilia' 'bahia' 'taubate' 'cascavael'
 'monteiro lobato' 'viana' 'paraiba do sul' 'mococa' 'sao roque' 'passos'
 'francisco beltrao' 'tocantins' 'porto belo' 'nova iguacu' 'icara'
 'lajeado' 'horizontina' 'votorantim' 'campo bom' 'monte alto'
 'fernandopolis' 'pedreira' 'poa' 'divinopolis' 'santa barbara d´oeste'
 'canoas' 'mombuca' 'sete lagoas' 'campo do meio' 'cordeiropolis'
 'uberlandia' 'santa barbara d oeste' 'volta redonda' '04482255'
 'aracatuba' 'monte siao' 'garuva' 'bonfinopolis de minas' 'cosmopolis'
 'pocos de caldas' 'artur nogueira' 'joao pessoa' 'dois corregos'
 'araquari' 'novo hamburgo, rio grande do sul, brasil' 'floranopolis'
 'sumare' 'guaira' 'cachoeiro de itapemirim' 'serrana' 'rolandia'
 'congonhas' 'sao  jose dos pinhais' 'boituva' 'mairipora' 'guaimbe'
 'parai' 'aperibe' 'jaguaruna' 'vila velha' 'juiz de fora' 'fronteira'
 'novo horizonte' 'pilar do sul' 'itajobi' 'cariacica / es' 'prados'
 'mucambo' 'montes claros' 'vicosa' 'porto velho' 'sao jose do rio pardo'
 'pato branco' 'sao joao del rei' 'presidente prudente' 'paracambi'
 'serra negra' 'sao caetano do sul' 'bom jardim' 'serra redonda'
 'sao francisco do sul' 'betim' 'imbituva' 'guaratuba' 'teresina'
 "sao miguel d'oeste" 'california' 'japira' 'foz do iguacu'
 'nova friburgo' 'itau de minas' 'oliveira' 'sabara' 'pedrinhas paulista'
 'votuporanga' 'holambra' 'ararangua' 'pinhais' 'pato bragado' 'carazinho'
 'arinos' 'sao pedro' 'lages' 'ampere' 'itauna' 'mogi mirim' 'curitibanos'
 'brasilia df' 'mogi das cruses' 'hortolandia' 'ipatinga' 'laguna'
 'dores de campos' 'sao paulo - sp' 'araras' 'divisa nova'
 'igaracu do tiete' 'pitangueiras' 'campo grande' 'garca'
 'presidente epitacio' 'sbc/sp' "arraial d'ajuda (porto seguro)"
 'pacatuba' 'formosa' 'borda da mata' 'ubatuba' 'entre rios do oeste'
 'formiga' 'venancio aires' 'navegantes' 'cruzeiro' 'santa maria' 'muriae'
 'santo andre/sao paulo' 'ipe' 'messias targino' 'varginha' 'botucatu'
 'domingos martins' 'uberaba' 'coronel fabriciano' 'cachoeirinha'
 's jose do rio preto' 'taruma' 'pirassununga' 'aruja' 'sp / sp'
 'angra dos reis' 'juzeiro do norte' 'laurentino' 'flores da cunha'
 'montenegro' 'pedregulho' 'novo hamburgo' 'torres' 'aracaju'
 'santa catarina' 'joao pinheiro' 'bady bassitt' 'sinop' 'guarapuava'
 'araucaria' 'vitoria' 'batatais' 'lagoa santa' 'chapeco' 'umuarama'
 'belford roxo' 'cariacica' 'monte alegre do sul' 'sp' 'lagoa da prata'
 'rolante' 'teresopolis' 'itaporanga' 'campo largo' 'sao joao de meriti'
 'maua/sao paulo' 'bom jesus dos perdoes' 'brotas' 'irece' 'coxim' 'jau'
 'conselheiro lafaiete' 'amparo' 'sao miguel do oeste' 'gaspar'
 'rio bonito' 'mandaguari' 'vargem grande paulista' 'conchal' 'cambe'
 'marialva' 'alfenas' 'balneario camboriu' 'palhoca'
 'sao bernardo do capo' 'guara' 'colatina' 'franco da rocha' 'lambari'
 'mogi das cruzes / sp' 'treze tilias' 'rio de janeiro \\rio de janeiro'
 'paulo lopes' 'santa cecilia' 'braco do norte' 'floresta' 'farroupilha'
 'castro' 'luziania' 'joao monlevade' 'pelotas' 'sao bento'
 'campos dos goytacazes' 'ouro fino' 'sao jose dos pinhas' 'tiete'
 'viamao' 'janauba' 'capivari' 'santa terezinha de itaipu' 'igrejinha'
 'sao bento do sul' 'duque de caxias' 'araxa' 'canoinhas' 'recife'
 'barbacena/ minas gerais' 'vera cruz' 'parnamirim' 'santo angelo'
 'paincandu' 'tres rios' 'tanabi' 'portoferreira' 'itatiba' 'sarandi'
 'cravinhos' 'morrinhos' 'bebedouro' 'almirante tamandare' 'bertioga'
 'natal' 'belo horizont' 'ivoti' 'andira-pr' 'cerqueira cesar' 'marapoama'
 'imigrante' 'mairinque' 'sao paulo sp' 'rio de janeiro / rio de janeiro'
 'andradas' 'sando andre' 'nova odessa' 'paulinia' 'extrema' 'olimpia'
 'angra dos reis rj' 'ronda alta' 'sao  paulo' 'sao vicente' 'pinhais/pr'
 'portao' 'registro' 'ao bernardo do campo' 'carmo do cajuru'
 'embu das artes' 'fernando prestes' 'castro pires' 'vargem grande do sul'
 'campina das missoes' 'sao pedro da aldeia' 'miguelopolis' 'itapui' 'sbc'
 'neopolis' 'mineiros do tiete' 'varzea paulista' 'nova lima' 'barbacena'
 'caieiras' 'buritama' 'erechim' 'itapetininga' 'pinhalzinho' 'descalvado'
 'pitanga' 'bage' 'taio' "santa barbara d'oeste" 'patos de minas'
 'garulhos' 'jarinu' 'nova petropolis' 'ribeirao preto / sao paulo'
 'camboriu' 'nova trento' 'sao luis' 'sao jose do rio pret' 'eusebio'
 'itaipulandia' 'ipira' 'campo magro' 'tiradentes' 'sao paluo' 'baependi'
 'embu guacu' 'paraiso do sul' 'aparecida' 'cataguases' 'bariri'
 'abadia de goias' 'alambari' 'ji parana' 'vassouras' 'lorena' 'rodeio'
 'louveira' 'guanhaes' 'santo antonio de padua' 'presidente getulio'
 'campos novos' 'eunapolis' 'engenheiro coelho' 'rio das pedras'
 'afonso claudio' 'carapicuiba / sao paulo' 'centro' 'parana' 'indaial'
 'bombinhas' 'orlandia' 'itapeva' 'sao sebastiao' 'macatuba'
 'sao joao da boa vista' 'teixeira soares' 'mandaguacu' 'rio do oeste'
 'vendas@creditparts.com.br' 'armacao dos buzios' 'mateus leme'
 'sao paulop' 'campo limpo paulista' 'socorro' 'serra' 'bocaiuva do sul'
 'ilheus' 'imbe' 'soledade' 'cajamar' 'rio negrinho' 'clementina'
 'francisco morato' 'rio grande' 'xaxim' 'manaus' 'terra boa'
 'minas gerais' 'avare' 'ibirite' 'santa maria da serra' 'auriflama'
 'condor' 'ibia' 'guanambi' 'caucaia' 'cordilheira alta' 'carmo da mata'
 'ouro preto' 'pedro leopoldo' 'santa rosa de viterbo' 'xanxere'
 'alvares machado' 'scao jose do rio pardo' 'ribeirao das neves'
 'medianeira' 'massaranduba' 'cornelio procopio' 'pirituba' 'jambeiro'
 'sao leopoldo' 'aguas claras df' 'ribeirao pretp' 'cianorte'
 'feira de santana' 'cachoeira do sul' 'guariba'
 'sao sebastiao da grama/sp' 'dracena' 'ourinhos' 'robeirao preto'
 'cacador' 'gama' 'queimados' 'cananeia' 'presidente bernardes' 'pinhalao'
 'sombrio' 'campo mourao' 'ilicinea' 'itabira' 'barrinha' 'jussara'
 'uniao da vitoria' 'triunfo' 'santa cruz do sul' 'colorado' 'itapema'
 'sapiranga' 'paranavai' 'alvorada' 'ipaussu' 'rio verde' 'mage'
 'tabao da serra' 'bofete' 'picarras' 'marica' 'jaragua'
 'governador valadares' 'rio de janeiro, rio de janeiro, brasil'
 'pouso alegre' 'timoteo' 'muqui' 'ipua' 'jacarei / sao paulo'
 'varzea alegre' 'guaratingueta' 'tambau' 'irati' 'riberao preto'
 'aparecida de goiania' 'bandeirantes' 'vitoria de santo antao' 'palotina'
 'leme']
# <seller_state>
number of unique values = 23
unique values = ['SP' 'RJ' 'PE' 'PR' 'GO' 'SC' 'BA' 'DF' 'RS' 'MG' 'RN' 'MT' 'CE' 'PB'
 'AC' 'ES' 'RO' 'PI' 'MS' 'SE' 'MA' 'AM' 'PA']

# payments

In [16]:
datasets['payments'].head()

,order_id,installments,sequential,payment_type,value
0,25e8ea4e93396b6fa0d3dd708e76c1bd,1,1,credit_card,65.71
1,ba78997921bbcdc1373bb41e913ab953,8,1,credit_card,107.78
2,42fdf880ba16b47b59251dd489d4441a,2,1,credit_card,128.45
3,771ee386b001f06208a7419e4fc1bbd7,1,1,credit_card,81.16
4,62fe0bd75deb58982ebf8e53a128a301,1,1,credit_card,15.82

In [6]:
datasets['payments'].shape

(97433, 5)

In [8]:
datasets['payments'].order_id.nunique()

93000

In [17]:
datasets['payments'].groupby('order_id').apply(lambda x : sum(x['value']))

order_id
0000f01da58c553799200eb71eb0563b     72.90
00010242fe8c5a6d1ba2dd792cb16214     72.19
00026c8a4fe2c14efa2afe807921981c    477.28
000312d02b605a8a630c3a9882793ffb    673.20
00042b26cf59d7ce69dfabb4e55b4fd9    218.04
00048cc3ae777c65dbb7d2a0634bc1ea     34.59
0004940968b6f9fdb7ef5bb315d3dd45     44.09
0004e45495a3c003903562f035a835ce     98.90
00054e8431b9d7675808bcb819fb4a32     31.75
000576fe39319847cbb9d288c5617fa6    880.75
000600fcb6cd339109fe8f27d7ce7bca     41.84
00063b381e2406b52ad429470734ebd5     57.98
0006ec9db01a64e59a68b2c340bf65a7     97.32
0008288aa423d2a3f00fcb17cd7d8719    126.54
000844e66735b6b771578023091a2a37     98.79
0009792311464db532ff765bf7b182ae    127.55
000a1a23c186e860e31dd744d93f059a    114.37
000a950f6be5856bec0567ebccfa5d54     41.42
000aed2e25dbad2f9ddb70584c5a2ded    152.77
000e8b0af0aac34c2d96d4baf5162ccf     72.22
000ed9901656cc1e7c2f973f8c6e2309    118.56
000f99bb272406acd1dce9b54895dd62     69.77
001021efaa8636c29475e7734483457d     64.10
0010b2e5201cc5f1ae7e9c6cc8f5bd00     65.50
00119ff934e539cf26f92b9ef0cdfed8    236.88
0011d82c4b53e22e84023405fb467e57    315.33
00125cb692d04887809806618a2a145f    135.41
0012c0691fc9e9904585a7982ebc3f3d    138.12
0013503b13da1eac686219390b7d641b    137.22
00137e170939bba5a3134e2386413108    421.65
                                     ...
ffeba575a4bb795de0386cf957b3c6c3     30.74
ffec6450964463cf91dbb7d7ba22b543     33.81
ffed7e90414c1477a6b92554661d465f    166.71
ffeeb911d070bea3dd20bd5fd01da5e8     95.69
ffef5373bf5a7f3209d5330de6253dbb     98.88
ffef98cd5ecdc992fefbd967549520dd    153.01
ffefb169ddf34cecc0622a6d3cc387f8    142.10
fff1e3e76b816bfe8ef16678cc53c643     86.85
fff1fe51c4f9bf5963d6329553269a12    736.09
fff2e9e3aa8644e19710216b4ef53ab2     86.15
fff37e5e209512db4dd1c8a03beed88b     58.16
fff3983dfa3c5a0d752d8d17baa406a0     80.44
fff674501b113ab737d4edc3e9bb44ca     55.17
fff6889749958e42b47a7977a4cf0ea0    123.60
fff6b8ca971f8e3ec822e99d0f2d3d21    215.83
fff70321841e2d34bb629d8f4e9e68c3    118.75
fff7c4452f050315db1b3f24d9df5fcd    756.91
fff81f66a219237ad51e628c210e066e    144.65
fff8287bbae429a99bb7e8c21d151c41    456.28
fff90cdcb3b2e6cfb397d05d562fd3fe    101.73
fff972a570e5ae1752dc1896258a6525    170.76
fff989f6b6cfb906d6c39ed78258ff90     79.73
fffa82886406ccf10c7b4e35c4ff2788    273.92
fffaf8a07a1dfd71f6997e2c694de14b     73.34
fffb0b1a50e65c449020434fa835e078     15.86
fffb9224b6fc7c43ebb0904318b10b5f    356.76
fffc6722901386c66d5f8009639fcb24    191.58
fffe18544ffabc95dfada21779c9644f     64.71
fffe7967a0e803b9331617191f6c7ed7    165.90
ffff4b4f540d2d98fae13222d4d3aec1     52.27
Length: 93000, dtype: float64

In [27]:
datasets['payments'].payment_type == 'boleto'

0        False
1        False
2        False
3        False
4        False
5         True
6        False
7         True
8        False
9        False
10       False
11        True
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25        True
26       False
27       False
28        True
29       False
         ...
97403    False
97404     True
97405    False
97406    False
97407     True
97408    False
97409    False
97410    False
97411    False
97412     True
97413    False
97414    False
97415    False
97416     True
97417    False
97418    False
97419    False
97420    False
97421    False
97422    False
97423    False
97424    False
97425    False
97426    False
97427    False
97428    False
97429    False
97430    False
97431    False
97432    False
Name: payment_type, Length: 97433, dtype: bool

In [29]:
datasets['payments'].loc[datasets['payments'].payment_type == 'boleto', 'value']

5         51.95
7        118.26
11        32.39
25       283.34
28        73.34
31       160.80
35       130.88
36       234.70
41       458.31
43        30.69
46       139.07
60        89.63
61       434.58
65        77.10
77        73.15
82        64.90
95       105.87
101       47.00
129       42.77
139       85.14
142       45.46
143      137.93
145      108.31
150       93.26
153      116.56
158       68.54
159      136.34
160       32.62
161       82.06
174       97.32
          ...
97262     40.76
97277    157.03
97280     48.79
97283    108.13
97287     56.08
97293     30.09
97298     38.11
97302     96.80
97318    106.31
97319     39.04
97320    435.96
97321     50.86
97328    309.22
97330     53.37
97331    147.67
97339     30.51
97341     75.17
97343    105.77
97348     41.69
97378    141.78
97380    150.14
97381     67.46
97383    320.58
97384    204.32
97392    116.24
97399     92.20
97404     94.99
97407    607.15
97412    398.64
97416    160.89
Name: value, Length: 18845, dtype: float64

In [35]:
datasets['payments'].groupby(['order_id','payment_type']).apply(lambda x : sum(x['value']))

order_id                          payment_type
0000f01da58c553799200eb71eb0563b  boleto           72.90
00010242fe8c5a6d1ba2dd792cb16214  credit_card      72.19
00026c8a4fe2c14efa2afe807921981c  boleto          477.28
000312d02b605a8a630c3a9882793ffb  credit_card     673.20
00042b26cf59d7ce69dfabb4e55b4fd9  credit_card     218.04
00048cc3ae777c65dbb7d2a0634bc1ea  boleto           34.59
0004940968b6f9fdb7ef5bb315d3dd45  voucher          44.09
0004e45495a3c003903562f035a835ce  credit_card      98.90
00054e8431b9d7675808bcb819fb4a32  credit_card      31.75
000576fe39319847cbb9d288c5617fa6  credit_card     880.75
000600fcb6cd339109fe8f27d7ce7bca  credit_card      41.84
00063b381e2406b52ad429470734ebd5  credit_card      57.98
0006ec9db01a64e59a68b2c340bf65a7  credit_card      97.32
0008288aa423d2a3f00fcb17cd7d8719  boleto          126.54
000844e66735b6b771578023091a2a37  boleto           98.79
0009792311464db532ff765bf7b182ae  boleto          127.55
000a1a23c186e860e31dd744d93f059a  boleto          114.37
000a950f6be5856bec0567ebccfa5d54  credit_card      41.42
000aed2e25dbad2f9ddb70584c5a2ded  credit_card     152.77
000e8b0af0aac34c2d96d4baf5162ccf  debit_card       72.22
000ed9901656cc1e7c2f973f8c6e2309  credit_card       7.10
                                  voucher         111.46
000f99bb272406acd1dce9b54895dd62  credit_card      69.77
001021efaa8636c29475e7734483457d  credit_card      64.10
0010b2e5201cc5f1ae7e9c6cc8f5bd00  credit_card      65.50
00119ff934e539cf26f92b9ef0cdfed8  credit_card     236.88
0011d82c4b53e22e84023405fb467e57  credit_card     315.33
00125cb692d04887809806618a2a145f  credit_card     135.41
0012c0691fc9e9904585a7982ebc3f3d  credit_card     138.12
0013503b13da1eac686219390b7d641b  boleto          137.22
                                                   ...
ffeba575a4bb795de0386cf957b3c6c3  credit_card      30.74
ffec6450964463cf91dbb7d7ba22b543  credit_card      33.81
ffed7e90414c1477a6b92554661d465f  credit_card     166.71
ffeeb911d070bea3dd20bd5fd01da5e8  credit_card      95.69
ffef5373bf5a7f3209d5330de6253dbb  credit_card      98.88
ffef98cd5ecdc992fefbd967549520dd  boleto          153.01
ffefb169ddf34cecc0622a6d3cc387f8  credit_card     142.10
fff1e3e76b816bfe8ef16678cc53c643  credit_card      86.85
fff1fe51c4f9bf5963d6329553269a12  credit_card     736.09
fff2e9e3aa8644e19710216b4ef53ab2  boleto           86.15
fff37e5e209512db4dd1c8a03beed88b  credit_card      58.16
fff3983dfa3c5a0d752d8d17baa406a0  credit_card      80.44
fff674501b113ab737d4edc3e9bb44ca  credit_card      55.17
fff6889749958e42b47a7977a4cf0ea0  credit_card     123.60
fff6b8ca971f8e3ec822e99d0f2d3d21  credit_card     215.83
fff70321841e2d34bb629d8f4e9e68c3  credit_card     118.75
fff7c4452f050315db1b3f24d9df5fcd  credit_card     756.91
fff81f66a219237ad51e628c210e066e  boleto          144.65
fff8287bbae429a99bb7e8c21d151c41  credit_card     456.28
fff90cdcb3b2e6cfb397d05d562fd3fe  credit_card     101.73
fff972a570e5ae1752dc1896258a6525  boleto          170.76
fff989f6b6cfb906d6c39ed78258ff90  credit_card      79.73
fffa82886406ccf10c7b4e35c4ff2788  credit_card     273.92
fffaf8a07a1dfd71f6997e2c694de14b  boleto           73.34
fffb0b1a50e65c449020434fa835e078  credit_card      15.86
fffb9224b6fc7c43ebb0904318b10b5f  boleto          356.76
fffc6722901386c66d5f8009639fcb24  boleto          191.58
fffe18544ffabc95dfada21779c9644f  credit_card      64.71
fffe7967a0e803b9331617191f6c7ed7  credit_card     165.90
ffff4b4f540d2d98fae13222d4d3aec1  credit_card      52.27
Length: 95173, dtype: float64

In [42]:
datasets['payments'].loc[datasets['payments']['installments']>=2,]['payment_type'].value_counts()

credit_card    49055
Name: payment_type, dtype: int64

In [31]:
datasets['payments'].groupby('order_id').apply(lambda x : x.loc[x.payment_type == 'boleto',].value.sum())

KeyboardInterrupt: