In [56]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib import rc
from matplotlib import font_manager
import pylab
import datetime



font_name = font_manager.FontProperties(fname = "/Library/Fonts/AppleGothic.ttf").get_name()
plt.rcParams["font.family"] = font_name
plt.rcParams['axes.unicode_minus'] = False

pd.set_option('display.max_columns',None)

In [52]:
m4 = pd.read_csv('./2개월모델/month4.csv')
m5 = pd.read_csv('./2개월모델/month5.csv')
m45 = pd.read_csv('./2개월모델/month45.csv')
m6 = pd.read_csv('./2개월모델/month6.csv')

m4 = m4.iloc[:,:-18]
m5 = m5.iloc[:,:-18]
m45 = m45.iloc[:,:-18]

In [190]:
m7 = pd.read_csv('./2개월모델/month7.csv')
m8 = pd.read_csv('./2개월모델/month8.csv')
m78 = pd.read_csv('./2개월모델/month78.csv')
m9 = pd.read_csv('./2개월모델/month9.csv')

m6 = m6.iloc[:,:-18]
m7 = m7.iloc[:,:-18]
m8 = m8.iloc[:,:-18]
m78 = m78.iloc[:,:-18]
m9 = m9.iloc[:,:-18]

In [191]:
m56 = pd.read_csv('./2개월모델/month56.csv')
m67 = pd.read_csv('./2개월모델/month67.csv')

m56 = m56.iloc[:,:-18]
m67 = m67.iloc[:,:-18]

In [8]:
data2 = pd.read_csv('podol_final2.csv')
data2 = data2.drop(columns='Unnamed: 0')
data2=data2.fillna(0)

In [14]:
M6 = data2[['CLAC3_NM','April','May','June']]

In [15]:
M6['April_May'] = M6['April'] + M6['May']

/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [17]:
M6.columns = ['CLAC3_NM','M4','M5','M6','M45']

In [18]:
M6.head()

        CLAC3_NM       M4       M5       M6      M45
0           2단우산     66.0     44.0     46.0    110.0
1           3단우산    442.0    364.0    267.0    806.0
2  BB/파운데이션/컴팩트류  11386.0  13304.0  12012.0  24690.0
3          DIY가구     61.0    406.0    550.0    467.0
4          DIY완구      0.0      0.0      0.0      0.0

In [19]:
data = m4.merge(m5,on='CLAC3_NM',how='outer')
data = data.merge(m45,on='CLAC3_NM',how='outer')
data = data.merge(M6,on='CLAC3_NM',how='outer')

In [32]:

[i for i in range(1,17,3)]

[1, 4, 7, 10, 13, 16]

In [35]:
loca4=m4.iloc[:,-18:]
loca5=m4.iloc[:,-18:]
loca6=m4.iloc[:,-18:]

m4px = loca4.iloc[:,[0,3,6,9,12,15]]
m5px = loca5.iloc[:,[0,3,6,9,12,15]]
m45px = loca6.iloc[:,[0,3,6,9,12,15]]

m4min = loca4.iloc[:,[i for i in range(1,17,3)]]
m5min = loca5.iloc[:,[i for i in range(1,17,3)]]
m45min = loca6.iloc[:,[i for i in range(1,17,3)]]

m4max = loca4.iloc[:,[i for i in range(2,18,3)]]
m5max = loca5.iloc[:,[i for i in range(2,18,3)]]
m45max = loca6.iloc[:,[i for i in range(2,18,3)]]

In [38]:

m4px['m4px_mean'] = m4px.mean(axis=1)
m5px['m5px_mean'] = m5px.mean(axis=1)
m45px['m45px_mean'] = m45px.mean(axis=1)

m4min['m4min_mean'] = m4min.mean(axis=1)
m5min['m5min_mean'] = m5min.mean(axis=1)
m45min['m45min_mean'] = m45min.mean(axis=1)


m4max['m4max_mean'] = m4max.mean(axis=1)
m5max['m5max_mean'] = m5max.mean(axis=1)
m45max['m45max_mean'] = m45max.mean(axis=1)

/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/Users/YiYoung/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

In [42]:
weather = pd.read_csv('./날씨, 미세먼지 크롤링/weather.csv')

In [157]:
dust = pd.read_csv('./날씨, 미세먼지 크롤링/dust.csv')

In [57]:
weather['DATE'] = weather.DATE.apply(lambda x: datetime.datetime.strptime(str(x),'%Y%m%d'))
wpt = weather.DATE.dt
wpt_prop = pd.DataFrame({'year':wpt.year,
             'month':wpt.month,
             'day':wpt.day
             })
weather= pd.concat([weather,wpt_prop],axis=1)
weather.head()

       ZON_NM       DATE WEATHER  T_MAX  T_MIN  year  month  day
0  Gangwon-do 2018-03-01       비   -2.0    4.0  2018      3    1
1  Gangwon-do 2018-03-02    구름조금   -6.0    5.0  2018      3    2
2  Gangwon-do 2018-03-03    구름조금   -1.0   17.0  2018      3    3
3  Gangwon-do 2018-03-04       비    7.0   16.0  2018      3    4
4  Gangwon-do 2018-03-05  비/진눈개비    0.0    9.0  2018      3    5

In [158]:
dust['DATE'] = dust.DATE.apply(lambda x: datetime.datetime.strptime(str(x),'%Y%m%d'))
dpt = dust.DATE.dt
dpt_prop = pd.DataFrame({'year':dpt.year,
             'month':dpt.month,
             'day':dpt.day
             })
dust = pd.concat([dust,dpt_prop],axis=1)
dust.head()

       ZON_NM       DATE    px_mean  px_max  year  month  day
0  Gangwon-do 2018-03-01  26.695652      47  2018      3    1
1  Gangwon-do 2018-03-02  49.000000      63  2018      3    2
2  Gangwon-do 2018-03-03  44.000000      60  2018      3    3
3  Gangwon-do 2018-03-04  18.739130      43  2018      3    4
4  Gangwon-do 2018-03-05   9.863636      33  2018      3    5

In [62]:
weather['ZON_NM'].unique()

array(['Gangwon-do', 'Gyeonggi-do', 'Gyeongsangnam-do',
       'Gyeongsangbuk-do', 'Gwangju', 'Daegu', 'Daejeon', 'Busan',
       'Seoul', 'Ulsan', 'Incheon', 'Jeollanam-do', 'Jeollabuk-do',
       'Jeju-do', 'Chungcheongnam-do', 'Chungcheongbuk-do', 'Sejong'],
      dtype=object)

In [159]:
zonname = []
for i in dust['ZON_NM']:
    if (i =='Seoul') | (i =='Gyeonggi-do') | (i=='Incheon'):
        zonname.append('수도권')
    elif (i == 'Jeollabuk-do') | (i =='Jeollanam-do') | (i=='Gwangju'):
        zonname.append('전라도')
    elif (i =='Busan') | (i =='Ulsan') | (i=='Gyeongsangnam-do')| (i =='Gyeongsangbuk-do') | (i=='Daegu'):
        zonname.append('경상도')
    elif (i =='Chungcheongnam-do') | (i =='Chungcheongbuk-do') | (i=='Daejeon'):
        zonname.append('충청도')
    elif i =='Gangwon-do':
        zonname.append('강원도')
    elif i =='Jeju-do':
        zonname.append('제주도')
    elif i == 'Sejong':
        zonname.append('세종시')
dust['ZON_NM'] = zonname

In [70]:
zonname = []
for i in weather['ZON_NM']:
    if (i =='Seoul') | (i =='Gyeonggi-do') | (i=='Incheon'):
        zonname.append('수도권')
    elif (i == 'Jeollabuk-do') | (i =='Jeollanam-do') | (i=='Gwangju'):
        zonname.append('전라도')
    elif (i =='Busan') | (i =='Ulsan') | (i=='Gyeongsangnam-do')| (i =='Gyeongsangbuk-do') | (i=='Daegu'):
        zonname.append('경상도')
    elif (i =='Chungcheongnam-do') | (i =='Chungcheongbuk-do') | (i=='Daejeon'):
        zonname.append('충청도')
    elif i =='Gangwon-do':
        zonname.append('강원도')
    elif i =='Jeju-do':
        zonname.append('제주도')
    elif i == 'Sejong':
        zonname.append('세종시')
weather['ZON_NM'] = zonname

In [72]:
zon_list = weather['ZON_NM'].unique()

In [73]:
zon_list

array(['강원도', '수도권', '경상도', '전라도', '충청도', '제주도', '세종시'], dtype=object)

In [79]:
meanweather = weather.groupby(['ZON_NM','month']).mean()

In [160]:
meandust = dust.groupby(['ZON_NM','month']).mean()

In [88]:
meanweather.reset_index(inplace=True)

In [161]:
meandust.reset_index(inplace=True)

In [249]:
val = []
for month in range(4,8):
    for zonname in zon_list:
        q = 'ZON_NM == "'+ zonname + '" & (month == ' + str(month) +'| month == ' +str(month+1) +')'
        val.append(meanweather.query(q)[['T_MAX','T_MIN']].mean().to_frame().T)

In [253]:
dval = []
for month in range(4,8):
    for zonname in zon_list:
        q = 'ZON_NM == "'+ zonname + '" & (month == ' + str(month) +'| month == ' +str(month+1) +')'
        
        dval.append(meandust.query(q)[['px_mean']].mean().to_frame().T)

In [121]:
m4temp = pd.concat(val[:7],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']

m4temp.columns= ['M4_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]

In [171]:
m4dust

      px_mean   px_mean    px_mean    px_mean    px_mean   px_mean  px_mean
1   43.851703       NaN        NaN        NaN        NaN       NaN      NaN
9         NaN       NaN  48.686746        NaN        NaN       NaN      NaN
17        NaN  44.09113        NaN        NaN        NaN       NaN      NaN
25        NaN       NaN        NaN  41.861123        NaN       NaN      NaN
33        NaN       NaN        NaN        NaN        NaN  38.01282      NaN
41        NaN       NaN        NaN        NaN  45.696037       NaN      NaN

In [173]:
m4dust = pd.concat(val[:7],axis=1)

m4dust.columns= ['M4_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]

In [130]:
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)

In [175]:
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)

In [150]:
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))

In [176]:
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))

In [177]:
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)

In [178]:
fm4 = pd.concat([fm4,p4],axis=1)

In [181]:
fm4.to_csv('./2개월모델/m4_2.csv',index=False,index_label= False)

In [207]:
m4temp = pd.concat(val[7:14],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M5_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm5 = pd.concat([m5,p4],axis=1)


m4dust = pd.concat(dval[7:14],axis=1)
m4dust.columns= ['M5_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm5 = pd.concat([fm5,p4],axis=1)

In [209]:
fm5.to_csv('./2개월모델/m5_2.csv',index=False,index_label= False)

In [210]:
m4temp = pd.concat(val[14:21],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M6_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm6 = pd.concat([m6,p4],axis=1)


m4dust = pd.concat(dval[14:21],axis=1)
m4dust.columns= ['M6_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm6 = pd.concat([fm6,p4],axis=1)

In [211]:
fm6.to_csv('./2개월모델/m6_2.csv',index=False,index_label= False)

In [212]:
m4temp = pd.concat(val[21:28],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M7_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm7 = pd.concat([m7,p4],axis=1)

m4dust = pd.concat(dval[21:28],axis=1)
m4dust.columns= ['M7_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm7 = pd.concat([fm7,p4],axis=1)

In [213]:
fm7.to_csv('./2개월모델/m7_2.csv',index=False,index_label= False)

In [214]:
m4temp = pd.concat(val[28:35],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M8_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm8 = pd.concat([m8,p4],axis=1)


m4dust = pd.concat(dval[28:35],axis=1)
m4dust.columns= ['M8_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm8 = pd.concat([fm8,p4],axis=1)

In [216]:
fm8.to_csv('./2개월모델/m8_2.csv',index=False,index_label= False)

In [220]:
m4temp = pd.concat(val[35:42],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M9_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm9 = pd.concat([m9,p4],axis=1)


m4dust = pd.concat(dval[35:42],axis=1)
m4dust.columns= ['M9_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm9 = pd.concat([fm9,p4],axis=1)

In [221]:
fm9.to_csv('./2개월모델/m9_2.csv',index=False,index_label= False)

In [254]:
m4temp = pd.concat(val[0:7],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M45_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm45 = pd.concat([m45,p4],axis=1)


m4dust = pd.concat(dval[0:7],axis=1)
m4dust.columns= ['M45_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm45 = pd.concat([fm45,p4],axis=1)

In [256]:
fm45.to_csv('./2개월모델/m45_2.csv',index=False,index_label= False)

In [257]:
m4temp = pd.concat(val[7:14],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M56_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm56 = pd.concat([m56,p4],axis=1)


m4dust = pd.concat(dval[7:14],axis=1)
m4dust.columns= ['M56_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm56 = pd.concat([fm56,p4],axis=1)

In [259]:
fm56.to_csv('./2개월모델/m56_2.csv',index=False,index_label= False)

In [260]:
m4temp = pd.concat(val[14:21],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M67_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm67 = pd.concat([m67,p4],axis=1)


m4dust = pd.concat(dval[14:21],axis=1)
m4dust.columns= ['M67_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm67 = pd.concat([fm67,p4],axis=1)

In [262]:
fm67.to_csv('./2개월모델/m67_2.csv',index=False,index_label= False)

In [263]:
m4temp = pd.concat(val[21:28],axis=1)
zon_list2 = ['강원도','강원도','수도권','수도권','경상도','경상도','전라도','전라도','충청도','충청도','제주도','제주도','세종시','세종시']
tlist = ['T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX','T_MIN','T_MAX']
m4temp.columns= ['M78_%s_%s'%(z,t) for z,t in zip(zon_list2,tlist)]
m4weather = m4temp.iloc[:,:-2]
m4weather.fillna(m4weather.mean(),inplace=True)
p4 = pd.DataFrame([m4weather.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm78 = pd.concat([m78,p4],axis=1)


m4dust = pd.concat(dval[21:28],axis=1)
m4dust.columns= ['M78_%s_%s'%(z,t) for z,t in zip(zon_list,m4dust.columns)]
m4dust = m4dust.iloc[:,:-1]
m4dust.fillna(m4dust.mean(),inplace=True)
p4 = pd.DataFrame([m4dust.iloc[0]]*len(m4))
p4 = p4.reset_index()
p4.drop(columns='index',inplace=True)
fm78 = pd.concat([fm78,p4],axis=1)

In [264]:
fm78.to_csv('./2개월모델/m78_2.csv',index=False,index_label= False)

In [49]:
m4px.drop(columns='m4px_mean',inplace=True)

/Users/YiYoung/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [131]:
m4.concat[[m4,m4weather]]

,CLAC3_NM,M4_F_TOT_SALES,M4_F_HITS_SEQ,M4_M_TOT_SALES,M4_M_HITS_SEQ,M4_10_TOT_SALES,M4_10_HITS_SEQ,M4_20_TOT_SALES,M4_20_HITS_SEQ,M4_30_TOT_SALES,M4_30_HITS_SEQ,M4_40_TOT_SALES,M4_40_HITS_SEQ,M4_50_TOT_SALES,M4_50_HITS_SEQ,M4_60_TOT_SALES,M4_60_HITS_SEQ,M4_F10_TOT_SALES,M4_F10_HITS_SEQ,M4_F20_TOT_SALES,M4_F20_HITS_SEQ,M4_F30_TOT_SALES,M4_F30_HITS_SEQ,M4_F40_TOT_SALES,M4_F40_HITS_SEQ,M4_F50_TOT_SALES,M4_F50_HITS_SEQ,M4_F60_TOT_SALES,M4_F60_HITS_SEQ,M4_M10_TOT_SALES,M4_M10_HITS_SEQ,M4_M20_TOT_SALES,M4_M20_HITS_SEQ,M4_M30_TOT_SALES,M4_M30_HITS_SEQ,M4_M40_TOT_SALES,M4_M40_HITS_SEQ,M4_M50_TOT_SALES,M4_M50_HITS_SEQ,M4_M60_TOT_SALES,M4_M60_HITS_SEQ,M4_수도권_TOT_SALES,M4_수도권_HITS_SEQ,M4_전라도_TOT_SALES,M4_전라도_HITS_SEQ,M4_경상도_TOT_SALES,M4_경상도_HITS_SEQ,M4_충청도_TOT_SALES,M4_충청도_HITS_SEQ,M4_강원도_TOT_SALES,M4_강원도_HITS_SEQ,M4_제주도_TOT_SALES,M4_제주도_HITS_SEQ
0,2단우산,44.0,89.320000,5.0,95.333333,NaN,NaN,1.0,162.000000,20.0,76.000000,24.0,88.750000,4.0,101.000000,NaN,NaN,NaN,NaN,NaN,NaN,20.0,76.000000,20.0,91.722222,4.0,101.000000,NaN,NaN,NaN,NaN,1.0,162.000000,NaN,NaN,4.0,62.000000,NaN,NaN,NaN,NaN,41.0,71.545455,3.0,52.000000,14.0,70.916667,7.0,110.600000,1.0,26.000000,NaN,NaN
1,3단우산,253.0,81.565445,44.0,59.714286,NaN,NaN,9.0,57.625000,90.0,82.492063,175.0,76.719424,22.0,88.733333,1.0,16.00000,NaN,NaN,7.0,58.500000,82.0,76.140351,151.0,82.593220,13.0,114.200000,NaN,NaN,NaN,NaN,2.0,55.000000,8.0,142.833333,24.0,43.714286,9.0,37.800000,1.0,16.000000,250.0,68.337662,21.0,80.062500,126.0,66.638554,29.0,91.680000,11.0,40.555556,2.0,21.50000
2,BB/파운데이션/컴팩트류,8402.0,65.852596,492.0,62.953811,47.0,53.116279,1851.0,63.750735,3864.0,66.590215,2641.0,66.115626,436.0,64.769029,55.0,66.72549,45.0,53.439024,1776.0,64.136225,3730.0,66.595029,2416.0,66.057613,389.0,66.640118,46.0,67.380952,2.0,46.5,75.0,53.890625,134.0,66.448276,225.0,66.750000,47.0,49.666667,9.0,63.666667,7088.0,60.782616,722.0,58.729102,2451.0,61.157800,642.0,59.062606,238.0,54.263736,112.0,60.85567
3,DIY가구,1.0,31.000000,57.0,80.363636,NaN,NaN,NaN,NaN,57.0,79.272727,1.0,43.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,84.100000,1.0,43.000000,NaN,NaN,NaN,NaN,61.0,73.066667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DSLR,18.0,68.944444,8.0,51.875000,NaN,NaN,4.0,93.000000,12.0,47.833333,8.0,75.875000,2.0,51.500000,NaN,NaN,NaN,NaN,4.0,93.000000,7.0,53.285714,5.0,78.600000,2.0,51.500000,NaN,NaN,NaN,NaN,NaN,NaN,5.0,40.200000,3.0,71.333333,NaN,NaN,NaN,NaN,88.0,41.102273,2.0,22.500000,10.0,55.300000,2.0,51.000000,NaN,NaN,1.0,12.00000

In [50]:
m4px = m4px.T.fillna(m4px.mean(axis=1)).T
#m5px.T.fillna(m5px.mean(axis=1)).T
#m45px.T.fillna(m45px.mean(axis=1)).T

In [23]:
data.fillna(0,inplace=True)
data.set_index('CLAC3_NM',inplace=True)

In [24]:
data.head()

,M4_F_TOT_SALES,M4_F_HITS_SEQ,M4_M_TOT_SALES,M4_M_HITS_SEQ,M4_10_TOT_SALES,M4_10_HITS_SEQ,M4_20_TOT_SALES,M4_20_HITS_SEQ,M4_30_TOT_SALES,M4_30_HITS_SEQ,M4_40_TOT_SALES,M4_40_HITS_SEQ,M4_50_TOT_SALES,M4_50_HITS_SEQ,M4_60_TOT_SALES,M4_60_HITS_SEQ,M4_F10_TOT_SALES,M4_F10_HITS_SEQ,M4_F20_TOT_SALES,M4_F20_HITS_SEQ,M4_F30_TOT_SALES,M4_F30_HITS_SEQ,M4_F40_TOT_SALES,M4_F40_HITS_SEQ,M4_F50_TOT_SALES,M4_F50_HITS_SEQ,M4_F60_TOT_SALES,M4_F60_HITS_SEQ,M4_M10_TOT_SALES,M4_M10_HITS_SEQ,M4_M20_TOT_SALES,M4_M20_HITS_SEQ,M4_M30_TOT_SALES,M4_M30_HITS_SEQ,M4_M40_TOT_SALES,M4_M40_HITS_SEQ,M4_M50_TOT_SALES,M4_M50_HITS_SEQ,M4_M60_TOT_SALES,M4_M60_HITS_SEQ,M4_수도권_TOT_SALES,M4_수도권_HITS_SEQ,M4_전라도_TOT_SALES,M4_전라도_HITS_SEQ,M4_경상도_TOT_SALES,M4_경상도_HITS_SEQ,M4_충청도_TOT_SALES,M4_충청도_HITS_SEQ,M4_강원도_TOT_SALES,M4_강원도_HITS_SEQ,M4_제주도_TOT_SALES,M4_제주도_HITS_SEQ,M4_수도권_PX_MEAN,M4_수도권_T_MIN,M4_수도권_T_MAX,M4_전라도_PX_MEAN,M4_전라도_T_MIN,M4_전라도_T_MAX,M4_경상도_PX_MEAN,M4_경상도_T_MIN,M4_경상도_T_MAX,M4_충청도_PX_MEAN,M4_충청도_T_MIN,M4_충청도_T_MAX,M4_강원도_PX_MEAN,M4_강원도_T_MIN,M4_강원도_T_MAX,M4_제주도_PX_MEAN,M4_제주도_T_MIN,M4_제주도_T_MAX,M5_F_TOT_SALES,M5_F_HITS_SEQ,M5_M_TOT_SALES,M5_M_HITS_SEQ,M5_10_TOT_SALES,M5_10_HITS_SEQ,M5_20_TOT_SALES,M5_20_HITS_SEQ,M5_30_TOT_SALES,M5_30_HITS_SEQ,M5_40_TOT_SALES,M5_40_HITS_SEQ,M5_50_TOT_SALES,M5_50_HITS_SEQ,M5_60_TOT_SALES,M5_60_HITS_SEQ,M5_F10_TOT_SALES,M5_F10_HITS_SEQ,M5_F20_TOT_SALES,M5_F20_HITS_SEQ,M5_F30_TOT_SALES,M5_F30_HITS_SEQ,M5_F40_TOT_SALES,M5_F40_HITS_SEQ,M5_F50_TOT_SALES,M5_F50_HITS_SEQ,M5_F60_TOT_SALES,M5_F60_HITS_SEQ,M5_M10_TOT_SALES,M5_M10_HITS_SEQ,M5_M20_TOT_SALES,M5_M20_HITS_SEQ,M5_M30_TOT_SALES,M5_M30_HITS_SEQ,M5_M40_TOT_SALES,M5_M40_HITS_SEQ,M5_M50_TOT_SALES,M5_M50_HITS_SEQ,M5_M60_TOT_SALES,M5_M60_HITS_SEQ,M5_수도권_TOT_SALES,M5_수도권_HITS_SEQ,M5_전라도_TOT_SALES,M5_전라도_HITS_SEQ,M5_경상도_TOT_SALES,M5_경상도_HITS_SEQ,M5_충청도_TOT_SALES,M5_충청도_HITS_SEQ,M5_강원도_TOT_SALES,M5_강원도_HITS_SEQ,M5_제주도_TOT_SALES,M5_제주도_HITS_SEQ,M5_수도권_PX_MEAN,M5_수도권_T_MIN,M5_수도권_T_MAX,M5_전라도_PX_MEAN,M5_전라도_T_MIN,M5_전라도_T_MAX,M5_경상도_PX_MEAN,M5_경상도_T_MIN,M5_경상도_T_MAX,M5_충청도_PX_MEAN,M5_충청도_T_MIN,M5_충청도_T_MAX,M5_강원도_PX_MEAN,M5_강원도_T_MIN,M5_강원도_T_MAX,M5_제주도_PX_MEAN,M5_제주도_T_MIN,M5_제주도_T_MAX,M45_F_TOT_SALES,M45_F_HITS_SEQ,M45_M_TOT_SALES,M45_M_HITS_SEQ,M45_10_TOT_SALES,M45_10_HITS_SEQ,M45_20_TOT_SALES,M45_20_HITS_SEQ,M45_30_TOT_SALES,M45_30_HITS_SEQ,M45_40_TOT_SALES,M45_40_HITS_SEQ,M45_50_TOT_SALES,M45_50_HITS_SEQ,M45_60_TOT_SALES,M45_60_HITS_SEQ,M45_F10_TOT_SALES,M45_F10_HITS_SEQ,M45_F20_TOT_SALES,M45_F20_HITS_SEQ,M45_F30_TOT_SALES,M45_F30_HITS_SEQ,M45_F40_TOT_SALES,M45_F40_HITS_SEQ,M45_F50_TOT_SALES,M45_F50_HITS_SEQ,M45_F60_TOT_SALES,M45_F60_HITS_SEQ,M45_M10_TOT_SALES,M45_M10_HITS_SEQ,M45_M20_TOT_SALES,M45_M20_HITS_SEQ,M45_M30_TOT_SALES,M45_M30_HITS_SEQ,M45_M40_TOT_SALES,M45_M40_HITS_SEQ,M45_M50_TOT_SALES,M45_M50_HITS_SEQ,M45_M60_TOT_SALES,M45_M60_HITS_SEQ,M45_수도권_TOT_SALES,M45_수도권_HITS_SEQ,M45_전라도_TOT_SALES,M45_전라도_HITS_SEQ,M45_경상도_TOT_SALES,M45_경상도_HITS_SEQ,M45_충청도_TOT_SALES,M45_충청도_HITS_SEQ,M45_강원도_TOT_SALES,M45_강원도_HITS_SEQ,M45_제주도_TOT_SALES,M45_제주도_HITS_SEQ,M45_수도권_PX_MEAN,M45_수도권_T_MIN,M45_수도권_T_MAX,M45_전라도_PX_MEAN,M45_전라도_T_MIN,M45_전라도_T_MAX,M45_경상도_PX_MEAN,M45_경상도_T_MIN,M45_경상도_T_MAX,M45_충청도_PX_MEAN,M45_충청도_T_MIN,M45_충청도_T_MAX,M45_강원도_PX_MEAN,M45_강원도_T_MIN,M45_강원도_T_MAX,M45_제주도_PX_MEAN,M45_제주도_T_MIN,M45_제주도_T_MAX,M4,M5,M6,M45
CLAC3_NM,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2단우산,44.0,89.320000,5.0,95.333333,0.0,0.000000,1.0,162.000000,20.0,76.000000,24.0,88.750000,4.0,101.000000,0.0,0.00000,0.0,0.000000,0.0,0.000000,20.0,76.000000,20.0,91.722222,4.0,101.000000,0.0,0.000000,0.0,0.0,1.0,162.000000,0.0,0.000000,4.0,62.000000,0.0,0.000000,0.0,0.000000,41.0,71.545455,3.0,52.000000,14.0,70.916667,7.0,110.600000,1.0,26.000000,0.0,0.00000,30.990961,7.590909,16.136364,47.041667,11.000000,23.000000,53.742397,10.416667,18.083333,31.438095,6.400000,15.400000,9.000000,8.000000,15.000000,0.000000,0.000000,0.000000,26.0,63.083333,7.0,31.250000,0.0,0.000000,0.0,0.000000,0.0,0.000000,28.0,58.400000,5.0,6.000000,0.0,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,21.0,68.272727,5.0,6.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,7.0,31.250000,0.0,0.000000,0.0,0.0,35.0,59.500000,0.0,0.000000,9.0,51.500000,0.0,0.000000,0.0,0.000000,0.0,0.00000,28.339524,14.818182,23.500000,0.000000,0.000000,0.000000,21.479167,12.750000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,70.0,80.810811,12.0,58.714286,0.0,0.000000,1.0,162.000000,20.0,76.000000,52.0,75.742857,9.0,69.333333,0.0,0.000000,0.0,0.000000,0.0,0.000000,20.0,76.000000,41.0,82.827586,9.0,69.333333,0.0,0.000000,0.0,0.0,1.0,162.000,0.0,0.000000,11.0,41.500000,0.0,0.000000,0.0,0.000000,76.0,65.522727,3.0,52.000000,23.0,66.062500,7.0,110.600000,1.0,26.000000,0.0,0.000000,29.665242,11.204545,19.818182,47.041667,11.000000,23.000000,45.676590,11.000000,17.812500,31.438095,6.400000,15.400000,9.000000,8.000000,15.000000,0.000000,0.000000,0.000000,66.0,44.0,46.0,110.0
3단우산,253.0,81.565445,44.0,59.714286,0.0,0.000000,9.0,57.625000,90.0,82.492063,175.0,76.719424,22.0,88.733333,1.0,16.00000,0.0,0.000000,7.0,58.500000,82.0,76.140351,151.0,82.593220,13.0,114.200000,0.0,0.000000,0.0,0.0,2.0,55.000000,8.0,142.833333,24.0,43.714286,9.0,37.800000,1.0,16.000000,250.0,68.337662,21.0,80.062500,126.0,66.638554,29.0,91.680000,11.0,40.555556,2.0,21.50000,33.018944,7.259740,16.064935,34.609372,9.937500,21.312500,40.875961,9.421687,17.325301,49.405880,5.960000,18.480000,36.864394,6.222222,17.666667,15.610746,13.500000,24.500000,228.0,77.735450,26.0,66.545455,0.0,0.000000,8.0,65.250000,86.0,81.395062,133.0,72.247525,22.0,90.625000,5.0,58.80000,0.0,0.000000,8.0,65.250000,80.0,82.680000,119.0,73.077778,18.0,88.846154,3.0,79.000000,0.0,0.0,0.0,0.000000,6.0,65.333333,14.0,65.454545,4.0,98.333333,2.0,28.5,226.0,65.435028,23.0,54.333333,92.0,83.513889,19.0,99.062500,0.0,0.000000,0.0,0.00000,36.559156,13.028249,22.237288,20.372585,17.277778,24.388889,29.461996,15.444444,22.902778,24.864026,14.437500,23.937500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,481.0,79.660526,70.0,62.350877,0.0,0.000000,17.0,61.437500,176.0,81.875000,308.0,74.837500,44.0,89.709677,6.0,51.666667,0.0,0.000000,15.0,62.357143,162.0,79.856061,270.0,78.475962,31.0,99.869565,3.0,79.000000,0.0,0.0,2.0,55.000,14.0,104.083333,38.0,51.187500,13.0,60.500000,3.0,24.333333,476.0,66.785498,44.0,66.441176,218.0,74.477419,48.0,94.560976,11.0,40.555556,2.0,21.500000,34.912048,10.344411,19.365559,27.072249,13.823529,22.941176,35.573990,12.219355,19.916129,39.828571,9.268293,20.609756,36.864394,6.222222,17.666667,15.610746,13.500000,24.500000,442.0,364.0,267.0,806.0
BB/파운데이션/컴팩트류,8402.0,65.852596,492.0,62.953811,47.0,53.116279,1851.0,63.750735,3864.0,66.590215,2641.0,66.115626,436.0,64.769029,55.0,66.72549,45.0,53.439024,1776.0,64.136225,3730.0,66.595029,2416.0,66.057613,389.0,66.640118,46.0,67.380952,2.0,46.5,75.0,53.890625,134.0,66.448276,225.0,66.750000,47.0,49.666667,9.0,63.666667,7088.0,60.782616,722.0,58.729102,2451.0,61.157800,642.0,59.062606,238.0,54.263736,112.0,60.85567,43.532522,7.868257,18.464383,43.011410,9.578947,20.009288,52.264990,10.467087,19.770063,46.212284,7.211506,20.253807,41.396398,7.038462,18.445055,38.308183,12.824742,19.453608,10103.0,66.543968,502.0,63.740492,63.0,49.920635,2414.0,61.785839,4739.0,67.893925,2858.0,68.126611,466.0,69.443902,65.0,57.52459,61.0,50.098361,2343.0,62.083071,4564.0,68.027672,2664.0,67.903580,411.0,71.493151,60.0,58.857143,2.0,44.5,71.0,50.934426,175.0,64.253247,194.0,71.172222,55.0,52.822222,5.0,42.6,8349.0,61.860431,846.0,66.308483,2804.0,63.698753,760.0,66.288984,188.0,61.442529,203.0,51.68595,37.627133,13.020638,23.213653,29.889927,14.569409,23.993573,33.456959,14.422837,22.432190,34.332498,13.457797,24.340486,30.407023,11.551724,23.385057,20.127694,17.099174,24.297521,18505.0,66.232658,994.0,63.353409,110.0,51.216981,4265.0,62.623715,8603.0,67.309059,5499.0,67.171343,902.0,67.192162,120.0,61.714286,106.0,51.441176,4119.0,62.952899,8294.0,67.383999,5080.0,67.034446,800.0,69.156250,106.0,62.510204,4.0,45.5,146.0,52.448,309.0,65.196296,419.0,68.844737,102.0,51.298851,14.0,56.142857,15437.0,61.372736,1568.0,62.870084,5255.0,62.520694,1402.0,62.978295,426.0,57.772472,315.0,55.766055,40.299229,10.689266,21.064682,35.842510,12.305478,22.186096,42.176904,12.588838,21.197952,39.775098,10.596124,22.468217,36.025187,9.244382,20.859551,28.217178,15.197248,22.142202,11386.0,13304.0,12012.0,24690.0
DIY가구,1.0,31.000000,57.0,80.363636,0.0,0.000000,0.0,0.000000,57.0,79.272727,1.0,43.000000,0.0,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.000000,1.0,31.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,56.0,84.100000,1.0,43.000000,0.0,0.000000,0.0,0.000000,61.0,73.066667,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,42.276976,10.533333,20.466667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145.0,54.600000,74.0,61.600000,0.0,0.000000,0.0,0.000000,51.0,31.666667,96.0,92.600000,72.0,11.500000,0.0,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.000000,73.0,83.333333,72.0,11.500000,0.0,0.000000,0.0,0.0,0.0,0.000000,51.0,31.666667,23.0,106.500000,0.0,0.000000,0.0,0.0,262.0,44.187500,0.0,0.000000,144.0,20.000000,0.0,0.000000,0.0,0.000000,0.0,0.00000,44.105066,12.187500,23.437500,0.000000,0.000000,0.000000,58.097222,13.000000,24.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,146.0,50.666667,131.0,74.500000,0.0,0.000000,0.0,0.000000,108.0,69.071429,97.0,84.333333,72.0,11.500000,0.0,0.000000,0.0,0.000000,0.0,0.000000,1.0,31.000000,73.0,83.333333,72.0,11.500000,0.0,0.000000,0.0,0.0,0.0,0.000,107.0,72.000000,24.0,85.333333,0.0,0.000000,0.0,0.000000,323.0,58.161290,0.0,0.000000,144.0,20.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,43.220506,11.387097,22.000000,0.000000,0.000000,0.000000,58.097222,13.000000,24.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,61.0,406.0,550.0,467.0
DSLR,18.0,68.944444,8.0,51.875000,0.0,0.000000,4.0,93.000000,12.0,47.833333,8.0,75.875000,2.0,51.500000,0.0,0.00000,0.0,0.000000,4.0,93.000000,7.0,53.285714,5.0,78.600000,2.0,51.500000,0.0,0.000000,0.0,0.0,0.0,0.000000,5.0,40.200000,3.0,71.333333,0.0,0.000000,0.0,0.000000,88.0,41.102273,2.0,22.500000,10.0,55.300000,2.0,51.000000,0.0,0.000000,1.0,12.00000,45.182482,6.215909,17.340909,36.266304,10.000000,15.000000,62.448810,9.000000,20.400000,74.645833,9.500000,21.000000,0.000000,0.000000,0.000000,38.625000,5.000000,10.000000,30.0,57.066667,16.0,67.000000,0.0,0.000000,7.0,66.857143,19.0,59.684211,17.0,65.058824,3.0,25.333333,0.0,0.00000,0.0,0.000000,3.0,30.000000,13.0,68.846154,11.0,59.181818,3.0,25.333333,0.0,0.000000,0.0,0.0,4.0,94.500000,6.0,39.833333,6.0,75.833333,0.0,0.000000,0.0,0.0,96.0,41.645833,6.0,79.333333,8.0,45.750000,9.0,29.222222,0.0,0.000000,0.0,0.00000,33.677010,13.125000,22.947917,18.152778,13.166667,21.333333,27.388244,12.125000,20.500000,38.685185,14.222222,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,48.0,61.520833,24.0,61.958333,0.0,0.000000,11.0,76.363636,31.0,55.096774,25.0,68.520000,5.0,35.800000,0.0,0.000000,0.0,0.000000,7.0,66.000000,20.0,63.400000,16.0,65.250000,5.0,35.800000,0.0,0.000000,0.0,0.0,4.0,94.500,11.0,40.000000,9.0,74.333333,0.0,0.000000,0.0,0.000000,184.0,41.385870,8.0,65.125000,18.0,51.055556,11.0,33.181818,0.0,0.000000,1.0,12.000000,39.179627,9.820652,20.266304,22.681159,12.375000,19.750000,46.866336,10.388889,20.444444,45.223485,13.363636,23.454545,0.000000,0.000000,0.000000,38.625000,5.000000,10.000000,108.0,119.0,115.0,227.0